const copy = {
  en: {eyebrow:'TRAVEL SAFETY, MADE CLEAR',title:'Know what’s happening.<br><em>Know what to do.</em>',intro:'Weather alerts and practical guidance for travellers, in a language you understand.',yourArea:'YOUR AREA',demoTitle:'Hackathon preview',demoText:'This screen uses sample information. It is not a live emergency service. Always follow current instructions from local authorities.',activeAlert:'SAMPLE WEATHER ALERT',highRisk:'HIGH RISK',alertTitle:'Heavy rain and local flooding',alertSummary:'Low-lying roads near the demo area may be waterlogged. Avoid walking or driving through floodwater.',updated:'Updated 20 min ago',sampleSource:'Sample source for demonstration',sampleSourceNote:'Not an official or live warning',whyShown:'Why am I seeing this?',rightNow:'RIGHT NOW',stepsTitle:'Stay safer',step1Title:'Move away from floodwater',step1Text:'Do not cross water on foot or in a vehicle. It may be deeper or faster than it looks.',step2Title:'Get to a secure place',step2Text:'Stay indoors and away from drains, underpasses, and exposed electrical equipment.',step3Title:'Check official updates',step3Text:'Follow current local authority instructions. Ask hotel staff or local officials for help.',nearbyHelp:'NEARBY HELP',helpTitle:'Safe places',viewAll:'View all',place1:'Community Relief Centre',place2:'Emergency Medical Help',placeStatus:'Sample listing · Confirm locally',helpNote:'Locations shown are illustrative. Confirm availability with local authorities.',infoStatus:'Information status',infoStatusText:'Demo content · No live feed connected',report:'Report a local concern',footer:'In an emergency, contact local emergency services.'},
  ta: {eyebrow:'பயண பாதுகாப்பு, தெளிவாக',title:'என்ன நடக்கிறது என்பதை அறியுங்கள்.<br><em>என்ன செய்ய வேண்டும் என்றும் அறியுங்கள்.</em>',intro:'பயணிகளுக்கான வானிலை எச்சரிக்கைகளும் நடைமுறை வழிகாட்டுதலும்.',yourArea:'உங்கள் பகுதி',demoTitle:'ஹேக்கத்தான் முன்னோட்டம்',demoText:'இது மாதிரி தகவல்களைப் பயன்படுத்துகிறது. இது நேரடி அவசர சேவை அல்ல. உள்ளூர் அதிகாரிகளின் தற்போதைய அறிவுறுத்தல்களைப் பின்பற்றுங்கள்.',activeAlert:'மாதிரி வானிலை எச்சரிக்கை',highRisk:'அதிக ஆபத்து',alertTitle:'கனமழை மற்றும் உள்ளூர் வெள்ளம்',alertSummary:'மாதிரி பகுதியில் தாழ்வான சாலைகளில் தண்ணீர் தேங்கியிருக்கலாம். வெள்ளநீரில் நடக்கவோ வாகனம் ஓட்டவோ வேண்டாம்.',updated:'20 நிமிடங்களுக்கு முன் புதுப்பிக்கப்பட்டது',sampleSource:'விளக்கத்திற்கான மாதிரி ஆதாரம்',sampleSourceNote:'அதிகாரப்பூர்வ அல்லது நேரடி எச்சரிக்கை அல்ல',whyShown:'இதை ஏன் பார்க்கிறேன்?',rightNow:'இப்போது',stepsTitle:'பாதுகாப்பாக இருங்கள்',step1Title:'வெள்ளநீரிலிருந்து விலகுங்கள்',step1Text:'நடந்தோ வாகனத்திலோ நீரைக் கடக்க வேண்டாம். ஆழமும் வேகமும் தெரியாமல் இருக்கலாம்.',step2Title:'பாதுகாப்பான இடத்திற்குச் செல்லுங்கள்',step2Text:'உள்ளே இருங்கள்; வடிகால்கள், சுரங்கப்பாதைகள், மின்சாதனங்களிலிருந்து விலகுங்கள்.',step3Title:'அதிகாரப்பூர்வ தகவலைப் பாருங்கள்',step3Text:'உள்ளூர் அதிகாரிகளின் அறிவுறுத்தல்களைப் பின்பற்றுங்கள். ஹோட்டல் ஊழியர்கள் அல்லது அதிகாரிகளிடம் உதவி கேளுங்கள்.',nearbyHelp:'அருகிலுள்ள உதவி',helpTitle:'பாதுகாப்பான இடங்கள்',viewAll:'அனைத்தையும் காண்க',place1:'சமூக நிவாரண மையம்',place2:'அவசர மருத்துவ உதவி',placeStatus:'மாதிரி பட்டியல் · உள்ளூரில் உறுதிசெய்யவும்',helpNote:'இடங்கள் விளக்கத்திற்காக மட்டுமே. உள்ளூர் அதிகாரிகளிடம் கிடைப்பதை உறுதிசெய்யவும்.',infoStatus:'தகவல் நிலை',infoStatusText:'மாதிரி உள்ளடக்கம் · நேரடி தகவல் இல்லை',report:'உள்ளூர் பிரச்சினையை தெரிவிக்கவும்',footer:'அவசரத்தில், உள்ளூர் அவசர சேவைகளைத் தொடர்புகொள்ளுங்கள்.'},
  hi: {eyebrow:'यात्रा सुरक्षा, स्पष्ट जानकारी',title:'जानें क्या हो रहा है।<br><em>जानें क्या करना है।</em>',intro:'यात्रियों के लिए मौसम अलर्ट और व्यावहारिक मार्गदर्शन, आपकी समझ की भाषा में।',yourArea:'आपका क्षेत्र',demoTitle:'हैकाथॉन पूर्वावलोकन',demoText:'यह स्क्रीन नमूना जानकारी दिखाती है। यह लाइव आपातकालीन सेवा नहीं है। स्थानीय अधिकारियों के मौजूदा निर्देश मानें।',activeAlert:'नमूना मौसम चेतावनी',highRisk:'उच्च जोखिम',alertTitle:'भारी बारिश और स्थानीय बाढ़',alertSummary:'डेमो क्षेत्र की निचली सड़कों पर पानी भर सकता है। बाढ़ के पानी में पैदल या वाहन से न जाएँ।',updated:'20 मिनट पहले अपडेट',sampleSource:'प्रदर्शन के लिए नमूना स्रोत',sampleSourceNote:'आधिकारिक या लाइव चेतावनी नहीं',whyShown:'यह क्यों दिख रहा है?',rightNow:'अभी',stepsTitle:'सुरक्षित रहें',step1Title:'बाढ़ के पानी से दूर रहें',step1Text:'पैदल या वाहन से पानी पार न करें। पानी दिखने से अधिक गहरा या तेज हो सकता है।',step2Title:'सुरक्षित जगह पर जाएँ',step2Text:'अंदर रहें और नालों, अंडरपास तथा खुले बिजली उपकरणों से दूर रहें।',step3Title:'आधिकारिक अपडेट देखें',step3Text:'स्थानीय अधिकारियों के निर्देश मानें। होटल कर्मचारियों या स्थानीय अधिकारियों से मदद लें।',nearbyHelp:'पास में सहायता',helpTitle:'सुरक्षित स्थान',viewAll:'सभी देखें',place1:'सामुदायिक राहत केंद्र',place2:'आपातकालीन चिकित्सा सहायता',placeStatus:'नमूना सूची · स्थानीय रूप से पुष्टि करें',helpNote:'स्थान केवल उदाहरण हैं। स्थानीय अधिकारियों से उपलब्धता की पुष्टि करें।',infoStatus:'जानकारी की स्थिति',infoStatusText:'डेमो सामग्री · लाइव फीड उपलब्ध नहीं',report:'स्थानीय समस्या बताएँ',footer:'आपातकाल में स्थानीय आपात सेवाओं से संपर्क करें.'}
};
Object.assign(copy.en, {yourArea:'DEMO AREA',areaLabel:'Adyar & nearby low-lying areas',liveSource:'Open IMD Chennai city warnings ↗',nearbyHelp:'OFFICIAL HELP',helpTitle:'Chennai contacts',disasterLine:'Disaster helpline',corporationLine:'Chennai Corporation',callFromPhone:'Call from your phone',helplineSource:'Numbers listed by Chennai District Administration.',verifyNumbers:'View source ↗',shareDemo:'Share this demo',infoStatus:'Information status',infoStatusText:'Demo content · No live feed connected',aboutTitle:'Clear information. Clear source.',aboutBody:'This prototype uses sample data so you can explore the experience. In a live service, alerts and safe-place information should show their issuing authority and the time they were last verified. Use local authority guidance in real emergencies.',copiedTitle:'Link copied',copiedBody:'The demo link and sample-data note are ready to share.',shareText:'StormSignal is a hackathon prototype. Its weather scenario is sample content, not a live warning.'});
Object.assign(copy.ta, {yourArea:'மாதிரி பகுதி',areaLabel:'அடையாறு மற்றும் அருகிலுள்ள தாழ்வான பகுதிகள்',liveSource:'IMD சென்னை நகர எச்சரிக்கைகளைத் திறக்கவும் ↗',nearbyHelp:'அதிகாரப்பூர்வ உதவி',helpTitle:'சென்னை தொடர்புகள்',disasterLine:'பேரிடர் உதவி எண்',corporationLine:'சென்னை மாநகராட்சி',callFromPhone:'தொலைபேசியில் அழைக்கவும்',helplineSource:'சென்னை மாவட்ட நிர்வாகம் வெளியிட்ட எண்கள்.',verifyNumbers:'ஆதாரத்தைப் பார்க்கவும் ↗',shareDemo:'இந்த டெமோவைப் பகிரவும்',infoStatus:'தகவல் நிலை',infoStatusText:'மாதிரி தகவல் · நேரடி தகவல் இணைப்பு இல்லை',aboutTitle:'தெளிவான தகவல். தெளிவான ஆதாரம்.',aboutBody:'இந்த முன்மாதிரி அனுபவத்தைப் பார்க்க மாதிரி தகவல்களைப் பயன்படுத்துகிறது. நேரடி சேவையில், எச்சரிக்கையின் அதிகாரப்பூர்வ மூலம் மற்றும் கடைசியாக சரிபார்க்கப்பட்ட நேரம் காட்டப்பட வேண்டும். உண்மையான அவசரத்தில் உள்ளூர் அதிகாரிகளின் அறிவுறுத்தல்களைப் பின்பற்றுங்கள்.',copiedTitle:'இணைப்பு நகலெடுக்கப்பட்டது',copiedBody:'மாதிரி தகவல் குறிப்புடன் கூடிய இணைப்பைப் பகிரலாம்.',shareText:'StormSignal ஒரு ஹேக்கத்தான் முன்மாதிரி. இதில் உள்ள வானிலை நிகழ்வு மாதிரி தகவல்; நேரடி எச்சரிக்கை அல்ல.'});
Object.assign(copy.hi, {yourArea:'डेमो क्षेत्र',areaLabel:'अड्यार और आसपास के निचले इलाके',liveSource:'IMD चेन्नई शहर की चेतावनी खोलें ↗',nearbyHelp:'आधिकारिक सहायता',helpTitle:'चेन्नई संपर्क',disasterLine:'आपदा हेल्पलाइन',corporationLine:'चेन्नई नगर निगम',callFromPhone:'फोन से कॉल करें',helplineSource:'चेन्नई जिला प्रशासन द्वारा सूचीबद्ध नंबर।',verifyNumbers:'स्रोत देखें ↗',shareDemo:'यह डेमो साझा करें',infoStatus:'जानकारी की स्थिति',infoStatusText:'डेमो सामग्री · लाइव फीड उपलब्ध नहीं',aboutTitle:'स्पष्ट जानकारी। स्पष्ट स्रोत।',aboutBody:'इस प्रोटोटाइप में अनुभव दिखाने के लिए नमूना डेटा है। वास्तविक सेवा में चेतावनी जारी करने वाले अधिकारी और आखिरी सत्यापन का समय दिखना चाहिए। असली आपातकाल में स्थानीय अधिकारियों के निर्देश मानें।',copiedTitle:'लिंक कॉपी हुआ',copiedBody:'डेमो लिंक और नमूना डेटा की जानकारी साझा करने के लिए तैयार है।',shareText:'StormSignal एक हैकाथॉन प्रोटोटाइप है। इसका मौसम परिदृश्य नमूना सामग्री है, लाइव चेतावनी नहीं।'});
copy.en.updated='Scenario timestamp · illustrative';
copy.ta.updated='மாதிரி நேரம் · விளக்கத்திற்காக';
copy.hi.updated='नमूना समय · केवल उदाहरण';
const dialog = document.querySelector('#dialog');
const dialogTitle = document.querySelector('#dialogTitle');
const dialogBody = document.querySelector('#dialogBody');
let currentLanguage = 'en';
function showDialog(title, body) { dialogTitle.textContent = title; dialogBody.textContent = body; dialog.showModal(); }
document.querySelectorAll('.close,.close-action').forEach(button => button.addEventListener('click', () => dialog.close()));
document.querySelector('#sourceInfo').addEventListener('click', () => showDialog(copy[currentLanguage].aboutTitle, copy[currentLanguage].aboutBody));
document.querySelector('#shareDemo').addEventListener('click', async () => {
  const strings = copy[currentLanguage];
  const shareData = {title:'StormSignal demo', text:strings.shareText, url:location.href};
  try {
    if (navigator.share) await navigator.share(shareData);
    else if (navigator.clipboard) { await navigator.clipboard.writeText(`${shareData.text} ${shareData.url}`); showDialog(strings.copiedTitle, strings.copiedBody); }
    else showDialog(strings.shareDemo, `${shareData.text} ${shareData.url}`);
  } catch (error) {
    if (error.name !== 'AbortError') showDialog(strings.shareDemo, `${shareData.text} ${shareData.url}`);
  }
});
document.querySelector('#language').addEventListener('change', event => {
  const strings = copy[event.target.value];
  currentLanguage = event.target.value;
  document.querySelectorAll('[data-i18n]').forEach(node => {
    const value = strings[node.dataset.i18n];
    if (value) node.innerHTML = value;
  });
  document.documentElement.lang = `${event.target.value}-IN`;
  try { localStorage.setItem('stormsignal-language', event.target.value); } catch {}
});
try {
  const savedLanguage = localStorage.getItem('stormsignal-language');
  if (savedLanguage && copy[savedLanguage]) {
    const selector = document.querySelector('#language');
    selector.value = savedLanguage;
    selector.dispatchEvent(new Event('change'));
  }
} catch {}

