const base = {
  status:'IMD district map · India',sourceName:'India Meteorological Department',sourceDetail:'Interactive district warnings across India · forecast dates shown by IMD',aboutLink:'How this works',languageLabel:'Language',installApp:'Install app',eyebrow:'TRAVEL SAFETY, MADE CLEAR',
  title:'Know what’s happening.<br><em>Know what to do.</em>',intro:'District weather warnings and practical guidance for travellers across India.',
  coverageLabel:'COVERAGE',coverage:'India · states and union territories',noticeTitle:'Official warnings, clearer next steps',
  noticeText:'StormSignal links you to the India Meteorological Department’s interactive district map. Check the district and forecast date there, then follow current local authority instructions.',
  alertLabel:'OFFICIAL DISTRICT WARNINGS · INDIA',liveSourceTag:'OFFICIAL IMD MAP',mapTitle:'Check the warning for your district',
  mapText:'Open IMD’s nationwide map, choose one of the available forecast dates, and select your district to read its warning.',
  legendTitle:'IMD warning levels',noWarning:'No warning',watch:'Watch',alert:'Alert',warning:'Warning',openMap:'Open India warning map ↗',
  rightNow:'RIGHT NOW',stepsTitle:'Stay safer while travelling',step1Title:'Check your district and date',
  step1Text:'Open the official map and read the warning for the place and day of your trip.',
  step2Title:'Avoid floodwater and exposed places',step2Text:'Never walk or drive through floodwater. Follow shelter or evacuation instructions from local authorities.',
  step3Title:'Recheck before you move',step3Text:'Warnings can change. Confirm the latest local instructions before travelling.',
  nearbyHelp:'NATIONWIDE EMERGENCY HELP',helpTitle:'Emergency response',emergencyNumber:'Call 112',
  emergencyDetail:'Pan-India emergency response number',helpNote:'For police, fire, medical, and other emergency assistance.',
  verifyNumbers:'Official 112 service ↗',infoStatus:'Source and scope',
  scopeText:'Warnings open on IMD’s official map; StormSignal is not an emergency service.',shareDemo:'Share this page',
  footer:'In an emergency, call 112 and follow local authority instructions.',aboutLabel:'ABOUT THIS SERVICE',
  aboutTitle:'Clear information. Clear source.',
  aboutBody:'StormSignal covers India by opening IMD’s public district-wise warning map. The map provides the official warning and forecast date for the district selected there. This prototype does not provide automatic location tracking, street-level conditions, shelters, evacuation routes, or rescue dispatch.',
  gotIt:'Got it',shareText:'StormSignal links travellers to India’s official district weather warnings and practical safety guidance. Check IMD’s map and follow local authority instructions.'
};

// Translations are concise summaries. The official IMD warning remains in its original wording on the source map.
const translated = {
  hi:{status:'IMD ज़िला मानचित्र · भारत',languageLabel:'भाषा',eyebrow:'यात्रा सुरक्षा, स्पष्ट जानकारी',title:'जानें क्या हो रहा है।<br><em>जानें क्या करना है।</em>',intro:'भारत भर के यात्रियों के लिए ज़िला मौसम चेतावनी और व्यावहारिक सलाह।',coverageLabel:'क्षेत्र',coverage:'भारत · राज्य और केंद्र शासित प्रदेश',noticeTitle:'आधिकारिक चेतावनी, स्पष्ट अगले कदम',noticeText:'StormSignal आपको भारत मौसम विज्ञान विभाग के इंटरैक्टिव ज़िला मानचित्र पर ले जाता है। वहाँ ज़िला और पूर्वानुमान की तारीख़ जाँचें, फिर स्थानीय अधिकारियों के निर्देश मानें।',alertLabel:'आधिकारिक ज़िला चेतावनी · भारत',liveSourceTag:'आधिकारिक IMD मानचित्र',mapTitle:'अपने ज़िले की चेतावनी देखें',mapText:'IMD का देशव्यापी मानचित्र खोलें, उपलब्ध तारीख़ चुनें और चेतावनी पढ़ने के लिए अपना ज़िला चुनें।',legendTitle:'IMD चेतावनी स्तर',noWarning:'चेतावनी नहीं',watch:'नज़र रखें',alert:'सतर्कता',warning:'चेतावनी',openMap:'भारत का चेतावनी मानचित्र खोलें ↗',rightNow:'अभी',stepsTitle:'यात्रा में सुरक्षित रहें',step1Title:'ज़िला और तारीख़ जाँचें',step1Text:'आधिकारिक मानचित्र पर अपनी जगह और यात्रा के दिन की चेतावनी पढ़ें।',step2Title:'बाढ़ के पानी और खुले स्थानों से बचें',step2Text:'बाढ़ के पानी में पैदल या वाहन से न जाएँ। स्थानीय अधिकारियों के आश्रय या निकासी निर्देश मानें।',step3Title:'आगे बढ़ने से पहले फिर जाँचें',step3Text:'चेतावनी बदल सकती है। यात्रा से पहले नवीनतम स्थानीय निर्देशों की पुष्टि करें।',nearbyHelp:'पूरे भारत में आपात सहायता',helpTitle:'आपातकालीन सहायता',emergencyNumber:'112 पर कॉल करें',emergencyDetail:'पूरे भारत का आपातकालीन नंबर',helpNote:'पुलिस, अग्निशमन, चिकित्सा और अन्य आपात सहायता के लिए।',verifyNumbers:'आधिकारिक 112 सेवा ↗',infoStatus:'स्रोत और दायरा',scopeText:'चेतावनी IMD के आधिकारिक मानचित्र पर खुलती है; StormSignal आपात सेवा नहीं है।',shareDemo:'यह पेज साझा करें',footer:'आपातकाल में 112 पर कॉल करें और स्थानीय अधिकारियों के निर्देश मानें।',aboutLabel:'इस सेवा के बारे में',aboutTitle:'स्पष्ट जानकारी। स्पष्ट स्रोत।',aboutBody:'StormSignal, IMD के सार्वजनिक ज़िला चेतावनी मानचित्र को खोलकर भारत के लिए चेतावनी दिखाता है। मानचित्र पर चुने गए ज़िले की आधिकारिक चेतावनी और तारीख़ देखें। यह प्रोटोटाइप स्थान ट्रैकिंग, सड़क-स्तर की स्थिति, आश्रय, निकासी मार्ग या बचाव सेवा नहीं देता।',gotIt:'समझ गया',shareText:'StormSignal यात्रियों को भारत की आधिकारिक ज़िला मौसम चेतावनी और सुरक्षा सलाह तक पहुँचाता है। IMD मानचित्र देखें और स्थानीय निर्देश मानें।'},
  ta:{status:'IMD மாவட்ட வரைபடம் · இந்தியா',languageLabel:'மொழி',eyebrow:'பயணப் பாதுகாப்பு, தெளிவாக',title:'என்ன நடக்கிறது என்பதை அறியுங்கள்.<br><em>என்ன செய்ய வேண்டும் என்றும் அறியுங்கள்.</em>',intro:'இந்தியா முழுவதும் பயணிகளுக்கான மாவட்ட வானிலை எச்சரிக்கைகளும் நடைமுறை வழிகாட்டுதலும்.',coverageLabel:'கவரேஜ்',coverage:'இந்தியா · மாநிலங்கள் மற்றும் யூனியன் பிரதேசங்கள்',noticeTitle:'அதிகாரப்பூர்வ எச்சரிக்கை, தெளிவான அடுத்த படிகள்',noticeText:'இந்திய வானிலை ஆய்வு மையத்தின் ஊடாடும் மாவட்ட வரைபடத்தை StormSignal திறக்கிறது. அங்கு மாவட்டத்தையும் முன்னறிவிப்பு நாளையும் பார்த்து, உள்ளூர் அதிகாரிகளின் அறிவுறுத்தல்களைப் பின்பற்றுங்கள்.',alertLabel:'அதிகாரப்பூர்வ மாவட்ட எச்சரிக்கைகள் · இந்தியா',liveSourceTag:'அதிகாரப்பூர்வ IMD வரைபடம்',mapTitle:'உங்கள் மாவட்ட எச்சரிக்கையைப் பாருங்கள்',mapText:'IMD-யின் இந்தியா முழுவதற்குமான வரைபடத்தைத் திறந்து, தேதியைத் தேர்ந்தெடுத்து உங்கள் மாவட்ட எச்சரிக்கையைப் படியுங்கள்.',legendTitle:'IMD எச்சரிக்கை நிலைகள்',noWarning:'எச்சரிக்கை இல்லை',watch:'கவனிக்கவும்',alert:'விழிப்புடன் இருங்கள்',warning:'எச்சரிக்கை',openMap:'இந்திய எச்சரிக்கை வரைபடத்தைத் திறக்கவும் ↗',rightNow:'இப்போது',stepsTitle:'பயணத்தில் பாதுகாப்பாக இருங்கள்',step1Title:'மாவட்டத்தையும் நாளையும் சரிபார்க்கவும்',step1Text:'அதிகாரப்பூர்வ வரைபடத்தில் உங்கள் இடம் மற்றும் பயண நாளுக்கான எச்சரிக்கையைப் பாருங்கள்.',step2Title:'வெள்ளநீர் மற்றும் திறந்த இடங்களைத் தவிர்க்கவும்',step2Text:'வெள்ளநீரில் நடக்கவோ வாகனம் ஓட்டவோ வேண்டாம். உள்ளூர் அதிகாரிகளின் தஞ்சம் அல்லது வெளியேற்ற அறிவுறுத்தல்களைப் பின்பற்றுங்கள்.',step3Title:'புறப்படுவதற்கு முன் மீண்டும் சரிபார்க்கவும்',step3Text:'எச்சரிக்கைகள் மாறலாம். பயணத்திற்கு முன் சமீபத்திய உள்ளூர் அறிவுறுத்தல்களை உறுதிப்படுத்துங்கள்.',nearbyHelp:'இந்தியா முழுவதும் அவசர உதவி',helpTitle:'அவசர உதவி',emergencyNumber:'112-ஐ அழைக்கவும்',emergencyDetail:'இந்தியா முழுவதற்குமான அவசர எண்',helpNote:'காவல், தீயணைப்பு, மருத்துவம் மற்றும் பிற அவசர உதவிக்கு.',verifyNumbers:'அதிகாரப்பூர்வ 112 சேவை ↗',infoStatus:'ஆதாரமும் வரம்பும்',scopeText:'எச்சரிக்கைகள் IMD அதிகாரப்பூர்வ வரைபடத்தில் திறக்கப்படும்; StormSignal அவசர சேவை அல்ல.',shareDemo:'இந்தப் பக்கத்தைப் பகிரவும்',footer:'அவசரத்தில் 112-ஐ அழைத்து உள்ளூர் அதிகாரிகளின் அறிவுறுத்தல்களைப் பின்பற்றுங்கள்.',aboutLabel:'இந்தச் சேவையைப் பற்றி',aboutTitle:'தெளிவான தகவல். தெளிவான ஆதாரம்.',aboutBody:'IMD-யின் பொது மாவட்ட எச்சரிக்கை வரைபடத்தைத் திறந்து இந்தியா முழுவதற்குமான எச்சரிக்கைகளை StormSignal காட்டுகிறது. அங்கு தேர்ந்தெடுத்த மாவட்டத்திற்கான அதிகாரப்பூர்வ எச்சரிக்கையும் தேதியும் கிடைக்கும். இந்த முன்மாதிரி இடக் கண்காணிப்பு, தெரு-நிலை நிலவரம், தங்குமிடம், வெளியேற்றப் பாதை அல்லது மீட்புச் சேவையை வழங்காது.',gotIt:'சரி',shareText:'இந்தியாவின் அதிகாரப்பூர்வ மாவட்ட வானிலை எச்சரிக்கைகளையும் பயணப் பாதுகாப்பு வழிகாட்டுதலையும் StormSignal இணைக்கிறது. IMD வரைபடத்தையும் உள்ளூர் அறிவுறுத்தல்களையும் பாருங்கள்.'},
  te:{status:'IMD జిల్లా మ్యాప్ · భారత్',languageLabel:'భాష',eyebrow:'ప్రయాణ భద్రత, స్పష్టంగా',title:'ఏం జరుగుతుందో తెలుసుకోండి.<br><em>ఏం చేయాలో తెలుసుకోండి.</em>',intro:'భారతదేశమంతటా ప్రయాణికుల కోసం జిల్లా వాతావరణ హెచ్చరికలు, ఆచరణాత్మక సూచనలు.',coverageLabel:'పరిధి',coverage:'భారతదేశం · రాష్ట్రాలు, కేంద్రపాలిత ప్రాంతాలు',noticeTitle:'అధికారిక హెచ్చరికలు, స్పష్టమైన తదుపరి చర్యలు',noticeText:'StormSignal భారత వాతావరణ శాఖ ఇంటరాక్టివ్ జిల్లా మ్యాప్‌కు తీసుకెళ్తుంది. అక్కడ జిల్లా, సూచన తేదీని చూసి స్థానిక అధికారుల తాజా సూచనలు పాటించండి.',alertLabel:'అధికారిక జిల్లా హెచ్చరికలు · భారతదేశం',liveSourceTag:'అధికారిక IMD మ్యాప్',mapTitle:'మీ జిల్లా హెచ్చరికను చూడండి',mapText:'IMD దేశవ్యాప్త మ్యాప్ తెరిచి, తేదీని ఎంచుకుని మీ జిల్లా హెచ్చరికను చదవండి.',legendTitle:'IMD హెచ్చరిక స్థాయిలు',noWarning:'హెచ్చరిక లేదు',watch:'గమనించండి',alert:'అప్రమత్తం',warning:'హెచ్చరిక',openMap:'భారత హెచ్చరిక మ్యాప్ తెరవండి ↗',rightNow:'ఇప్పుడే',stepsTitle:'ప్రయాణంలో సురక్షితంగా ఉండండి',step1Title:'జిల్లా, తేదీ చూడండి',step1Text:'అధికారిక మ్యాప్‌లో మీ ప్రాంతం, ప్రయాణ తేదీకి సంబంధించిన హెచ్చరిక చదవండి.',step2Title:'వరద నీరు, బహిరంగ ప్రదేశాలకు దూరంగా ఉండండి',step2Text:'వరద నీటిలో నడవకండి లేదా వాహనం నడపకండి. స్థానిక అధికారుల ఆశ్రయం లేదా తరలింపు సూచనలు పాటించండి.',step3Title:'బయలుదేరే ముందు మళ్లీ చూడండి',step3Text:'హెచ్చరికలు మారవచ్చు. ప్రయాణానికి ముందు తాజా స్థానిక సూచనలు నిర్ధారించుకోండి.',nearbyHelp:'దేశవ్యాప్త అత్యవసర సహాయం',helpTitle:'అత్యవసర స్పందన',emergencyNumber:'112కు కాల్ చేయండి',emergencyDetail:'భారతదేశమంతటా అత్యవసర నంబర్',helpNote:'పోలీస్, అగ్నిమాపక, వైద్య మరియు ఇతర అత్యవసర సహాయం కోసం.',verifyNumbers:'అధికారిక 112 సేవ ↗',infoStatus:'మూలం, పరిధి',scopeText:'హెచ్చరికలు IMD అధికారిక మ్యాప్‌లో తెరుచుకుంటాయి; StormSignal అత్యవసర సేవ కాదు.',shareDemo:'ఈ పేజీని పంచుకోండి',footer:'అత్యవసరంలో 112కు కాల్ చేసి స్థానిక అధికారుల సూచనలు పాటించండి.',aboutLabel:'ఈ సేవ గురించి',aboutTitle:'స్పష్టమైన సమాచారం. స్పష్టమైన మూలం.',aboutBody:'IMD ప్రజా జిల్లా హెచ్చరిక మ్యాప్‌ను తెరిచి StormSignal భారతదేశ వ్యాప్తంగా సమాచారాన్ని అందిస్తుంది. అక్కడ ఎంచుకున్న జిల్లాకు అధికారిక హెచ్చరిక, సూచన తేదీ కనిపిస్తాయి. ఈ నమూనా స్థానం ట్రాకింగ్, వీధి స్థాయి పరిస్థితులు, ఆశ్రయాలు, తరలింపు మార్గాలు లేదా రక్షణ సేవ ఇవ్వదు.',gotIt:'సరే',shareText:'StormSignal భారతదేశ అధికారిక జిల్లా వాతావరణ హెచ్చరికలు, ప్రయాణ భద్రత సూచనలకు అనుసంధానిస్తుంది. IMD మ్యాప్ చూడండి, స్థానిక సూచనలు పాటించండి.'},
  bn:{status:'IMD জেলা মানচিত্র · ভারত',languageLabel:'ভাষা',eyebrow:'ভ্রমণ নিরাপত্তা, সহজভাবে',title:'কী ঘটছে জানুন।<br><em>কী করতে হবে জানুন।</em>',intro:'ভারতজুড়ে ভ্রমণকারীদের জন্য জেলার আবহাওয়া সতর্কতা ও ব্যবহারিক পরামর্শ।',coverageLabel:'পরিধি',coverage:'ভারত · রাজ্য ও কেন্দ্রশাসিত অঞ্চল',noticeTitle:'সরকারি সতর্কতা, পরবর্তী পদক্ষেপ স্পষ্ট',noticeText:'StormSignal আপনাকে ভারতের আবহাওয়া দপ্তরের ইন্টার্যাক্টিভ জেলা মানচিত্রে নিয়ে যায়। সেখানে জেলা ও পূর্বাভাসের তারিখ দেখে স্থানীয় কর্তৃপক্ষের নির্দেশ মানুন।',alertLabel:'সরকারি জেলা সতর্কতা · ভারত',liveSourceTag:'সরকারি IMD মানচিত্র',mapTitle:'আপনার জেলার সতর্কতা দেখুন',mapText:'IMD-র সারা ভারতের মানচিত্র খুলুন, তারিখ বেছে নিয়ে জেলার সতর্কতা পড়ুন।',legendTitle:'IMD সতর্কতার স্তর',noWarning:'সতর্কতা নেই',watch:'নজর রাখুন',alert:'সতর্ক হন',warning:'সতর্কতা',openMap:'ভারতের সতর্কতা মানচিত্র খুলুন ↗',rightNow:'এখনই',stepsTitle:'ভ্রমণে নিরাপদ থাকুন',step1Title:'জেলা ও তারিখ দেখুন',step1Text:'সরকারি মানচিত্রে ভ্রমণের স্থান ও দিনের সতর্কতা পড়ুন।',step2Title:'বন্যার জল ও খোলা জায়গা এড়িয়ে চলুন',step2Text:'বন্যার জলে হাঁটবেন না বা গাড়ি চালাবেন না। স্থানীয় কর্তৃপক্ষের আশ্রয় বা সরিয়ে নেওয়ার নির্দেশ মানুন।',step3Title:'রওনা হওয়ার আগে আবার দেখুন',step3Text:'সতর্কতা বদলাতে পারে। ভ্রমণের আগে সর্বশেষ স্থানীয় নির্দেশ নিশ্চিত করুন।',nearbyHelp:'সারা দেশের জরুরি সহায়তা',helpTitle:'জরুরি সহায়তা',emergencyNumber:'112-এ কল করুন',emergencyDetail:'সারা ভারতের জরুরি নম্বর',helpNote:'পুলিশ, দমকল, চিকিৎসা ও অন্যান্য জরুরি সহায়তার জন্য।',verifyNumbers:'সরকারি 112 পরিষেবা ↗',infoStatus:'উৎস ও পরিধি',scopeText:'সতর্কতা IMD-র সরকারি মানচিত্রে খুলবে; StormSignal জরুরি পরিষেবা নয়।',shareDemo:'এই পৃষ্ঠা শেয়ার করুন',footer:'জরুরি অবস্থায় 112-এ কল করুন এবং স্থানীয় নির্দেশ মানুন।',aboutLabel:'এই পরিষেবা সম্পর্কে',aboutTitle:'স্পষ্ট তথ্য। স্পষ্ট উৎস।',aboutBody:'IMD-র সর্বসাধারণের জেলা সতর্কতা মানচিত্র খুলে StormSignal ভারতজুড়ে সতর্কতা দেখায়। সেখানে নির্বাচিত জেলার সরকারি সতর্কতা ও পূর্বাভাসের তারিখ দেখুন। এই প্রোটোটাইপ অবস্থান ট্র্যাকিং, রাস্তার অবস্থা, আশ্রয়কেন্দ্র, সরিয়ে নেওয়ার পথ বা উদ্ধার পরিষেবা দেয় না।',gotIt:'ঠিক আছে',shareText:'StormSignal ভারতের সরকারি জেলা আবহাওয়া সতর্কতা ও ভ্রমণ নিরাপত্তা নির্দেশনার সঙ্গে যুক্ত করে। IMD মানচিত্র দেখুন এবং স্থানীয় নির্দেশ মানুন।'},
  mr:{status:'IMD जिल्हा नकाशा · भारत',languageLabel:'भाषा',eyebrow:'प्रवास सुरक्षा, स्पष्टपणे',title:'काय घडत आहे ते जाणून घ्या.<br><em>काय करायचे ते जाणून घ्या.</em>',intro:'भारतभरातील प्रवाशांसाठी जिल्हा हवामान इशारे आणि व्यावहारिक मार्गदर्शन.',coverageLabel:'व्याप्ती',coverage:'भारत · राज्ये आणि केंद्रशासित प्रदेश',noticeTitle:'अधिकृत इशारे, पुढील पावले स्पष्ट',noticeText:'StormSignal तुम्हाला भारतीय हवामान विभागाच्या परस्परसंवादी जिल्हा नकाशावर नेतो. तेथे जिल्हा आणि अंदाजाची तारीख पाहून स्थानिक अधिकाऱ्यांच्या सूचना पाळा.',alertLabel:'अधिकृत जिल्हा इशारे · भारत',liveSourceTag:'अधिकृत IMD नकाशा',mapTitle:'तुमच्या जिल्ह्याचा इशारा पाहा',mapText:'IMD चा देशव्यापी नकाशा उघडा, तारीख निवडा आणि जिल्ह्याचा इशारा वाचा.',legendTitle:'IMD इशारा पातळ्या',noWarning:'इशारा नाही',watch:'लक्ष ठेवा',alert:'सावधान',warning:'इशारा',openMap:'भारताचा इशारा नकाशा उघडा ↗',rightNow:'आत्ताच',stepsTitle:'प्रवासात सुरक्षित राहा',step1Title:'जिल्हा आणि तारीख तपासा',step1Text:'अधिकृत नकाशावर प्रवासाच्या ठिकाणाचा आणि दिवसाचा इशारा वाचा.',step2Title:'पूराचे पाणी आणि उघडी ठिकाणे टाळा',step2Text:'पूराच्या पाण्यातून चालू किंवा वाहन चालवू नका. स्थानिक अधिकाऱ्यांच्या निवारा किंवा स्थलांतर सूचना पाळा.',step3Title:'निघण्यापूर्वी पुन्हा तपासा',step3Text:'इशारे बदलू शकतात. प्रवासापूर्वी नवीनतम स्थानिक सूचनांची खात्री करा.',nearbyHelp:'देशभरातील आपत्कालीन मदत',helpTitle:'आपत्कालीन प्रतिसाद',emergencyNumber:'112 वर कॉल करा',emergencyDetail:'भारतभरातील आपत्कालीन क्रमांक',helpNote:'पोलीस, अग्निशमन, वैद्यकीय आणि इतर आपत्कालीन मदतीसाठी.',verifyNumbers:'अधिकृत 112 सेवा ↗',infoStatus:'स्रोत आणि व्याप्ती',scopeText:'इशारे IMD च्या अधिकृत नकाशावर उघडतात; StormSignal आपत्कालीन सेवा नाही.',shareDemo:'हे पान शेअर करा',footer:'आपत्कालीन स्थितीत 112 वर कॉल करा आणि स्थानिक अधिकाऱ्यांच्या सूचना पाळा.',aboutLabel:'या सेवेबद्दल',aboutTitle:'स्पष्ट माहिती. स्पष्ट स्रोत.',aboutBody:'IMD चा सार्वजनिक जिल्हा इशारा नकाशा उघडून StormSignal भारतभराची माहिती दाखवते. तेथे निवडलेल्या जिल्ह्याचा अधिकृत इशारा आणि तारीख मिळते. हा नमुना स्थान ट्रॅकिंग, रस्त्यावरील परिस्थिती, निवारा, स्थलांतर मार्ग किंवा बचाव सेवा देत नाही.',gotIt:'समजले',shareText:'StormSignal भारताचे अधिकृत जिल्हा हवामान इशारे आणि प्रवास सुरक्षा मार्गदर्शन दाखवते. IMD नकाशा पाहा आणि स्थानिक सूचना पाळा.'},
  gu:{status:'IMD જિલ્લાનો નકશો · ભારત',languageLabel:'ભાષા',eyebrow:'મુસાફરી સુરક્ષા, સ્પષ્ટ રીતે',title:'શું થઈ રહ્યું છે તે જાણો.<br><em>શું કરવું તે જાણો.</em>',intro:'ભારતભરના પ્રવાસીઓ માટે જિલ્લા હવામાન ચેતવણીઓ અને ઉપયોગી માર્ગદર્શન.',coverageLabel:'વિસ્તાર',coverage:'ભારત · રાજ્યો અને કેન્દ્રશાસિત પ્રદેશો',noticeTitle:'સત્તાવાર ચેતવણીઓ, આગળનાં પગલાં સ્પષ્ટ',noticeText:'StormSignal તમને ભારતીય હવામાન વિભાગના ઇન્ટરેક્ટિવ જિલ્લા નકશા પર લઈ જાય છે. ત્યાં જિલ્લો અને આગાહીની તારીખ તપાસો અને સ્થાનિક અધિકારીઓની સૂચનાઓ અનુસરો.',alertLabel:'સત્તાવાર જિલ્લા ચેતવણીઓ · ભારત',liveSourceTag:'સત્તાવાર IMD નકશો',mapTitle:'તમારા જિલ્લાની ચેતવણી જુઓ',mapText:'IMDનો દેશવ્યાપી નકશો ખોલો, તારીખ પસંદ કરો અને તમારા જિલ્લાની ચેતવણી વાંચો.',legendTitle:'IMD ચેતવણી સ્તરો',noWarning:'ચેતવણી નથી',watch:'ધ્યાન રાખો',alert:'સાવચેત',warning:'ચેતવણી',openMap:'ભારતનો ચેતવણી નકશો ખોલો ↗',rightNow:'હમણાં',stepsTitle:'મુસાફરીમાં સુરક્ષિત રહો',step1Title:'જિલ્લો અને તારીખ તપાસો',step1Text:'સત્તાવાર નકશામાં સ્થળ અને મુસાફરીના દિવસની ચેતવણી વાંચો.',step2Title:'પૂરના પાણી અને ખુલ્લાં સ્થળોથી દૂર રહો',step2Text:'પૂરના પાણીમાં ચાલશો કે વાહન ચલાવશો નહીં. સ્થાનિક અધિકારીઓની આશ્રય અથવા સ્થળાંતર સૂચનાઓ અનુસરો.',step3Title:'નીકળતા પહેલાં ફરી તપાસો',step3Text:'ચેતવણીઓ બદલાઈ શકે છે. મુસાફરી પહેલાં નવીનતમ સ્થાનિક સૂચનાઓ ખાતરી કરો.',nearbyHelp:'સમગ્ર ભારતની કટોકટી મદદ',helpTitle:'કટોકટી પ્રતિસાદ',emergencyNumber:'112 પર કૉલ કરો',emergencyDetail:'ભારતભરનો કટોકટી નંબર',helpNote:'પોલીસ, અગ્નિશમન, તબીબી અને અન્ય કટોકટી સહાય માટે.',verifyNumbers:'સત્તાવાર 112 સેવા ↗',infoStatus:'સ્રોત અને વ્યાપ',scopeText:'ચેતવણીઓ IMDના સત્તાવાર નકશામાં ખુલશે; StormSignal કટોકટી સેવા નથી.',shareDemo:'આ પેજ શેર કરો',footer:'કટોકટીમાં 112 પર કૉલ કરો અને સ્થાનિક અધિકારીઓની સૂચનાઓ અનુસરો.',aboutLabel:'આ સેવા વિશે',aboutTitle:'સ્પષ્ટ માહિતી. સ્પષ્ટ સ્રોત.',aboutBody:'IMDના જાહેર જિલ્લા ચેતવણી નકશા દ્વારા StormSignal ભારતભરની ચેતવણી બતાવે છે. ત્યાં પસંદ કરેલા જિલ્લાની સત્તાવાર ચેતવણી અને તારીખ જુઓ. આ નમૂનો સ્થાન ટ્રેકિંગ, રસ્તાની સ્થિતિ, આશ્રયસ્થાનો, સ્થળાંતર માર્ગ કે બચાવ સેવા આપતો નથી.',gotIt:'બરાબર',shareText:'StormSignal ભારતની સત્તાવાર જિલ્લા હવામાન ચેતવણીઓ અને મુસાફરી સુરક્ષા માર્ગદર્શન સાથે જોડે છે. IMD નકશો જુઓ અને સ્થાનિક સૂચનાઓ અનુસરો.'},
  kn:{status:'IMD ಜಿಲ್ಲಾ ನಕ್ಷೆ · ಭಾರತ',languageLabel:'ಭಾಷೆ',eyebrow:'ಪ್ರಯಾಣ ಸುರಕ್ಷತೆ, ಸ್ಪಷ್ಟವಾಗಿ',title:'ಏನಾಗುತ್ತಿದೆ ತಿಳಿಯಿರಿ.<br><em>ಏನು ಮಾಡಬೇಕು ತಿಳಿಯಿರಿ.</em>',intro:'ಭಾರತದಾದ್ಯಂತ ಪ್ರಯಾಣಿಕರಿಗೆ ಜಿಲ್ಲಾ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆಗಳು ಮತ್ತು ಪ್ರಾಯೋಗಿಕ ಮಾರ್ಗದರ್ಶನ.',coverageLabel:'ವ್ಯಾಪ್ತಿ',coverage:'ಭಾರತ · ರಾಜ್ಯಗಳು ಮತ್ತು ಕೇಂದ್ರಾಡಳಿತ ಪ್ರದೇಶಗಳು',noticeTitle:'ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆಗಳು, ಮುಂದಿನ ಕ್ರಮಗಳು ಸ್ಪಷ್ಟ',noticeText:'StormSignal ನಿಮ್ಮನ್ನು ಭಾರತೀಯ ಹವಾಮಾನ ಇಲಾಖೆಯ ಸಂವಾದಾತ್ಮಕ ಜಿಲ್ಲಾ ನಕ್ಷೆಗೆ ಕರೆದೊಯ್ಯುತ್ತದೆ. ಅಲ್ಲಿ ಜಿಲ್ಲೆ ಮತ್ತು ಮುನ್ಸೂಚನೆ ದಿನಾಂಕ ನೋಡಿ ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳ ಸೂಚನೆ ಪಾಲಿಸಿ.',alertLabel:'ಅಧಿಕೃತ ಜಿಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು · ಭಾರತ',liveSourceTag:'ಅಧಿಕೃತ IMD ನಕ್ಷೆ',mapTitle:'ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಎಚ್ಚರಿಕೆ ಪರಿಶೀಲಿಸಿ',mapText:'IMDಯ ರಾಷ್ಟ್ರವ್ಯಾಪಿ ನಕ್ಷೆ ತೆರೆಯಿರಿ, ದಿನಾಂಕ ಆಯ್ಕೆ ಮಾಡಿ, ನಿಮ್ಮ ಜಿಲ್ಲೆಯ ಎಚ್ಚರಿಕೆ ಓದಿ.',legendTitle:'IMD ಎಚ್ಚರಿಕೆ ಮಟ್ಟಗಳು',noWarning:'ಎಚ್ಚರಿಕೆ ಇಲ್ಲ',watch:'ಗಮನಿಸಿ',alert:'ಎಚ್ಚರಿಕೆ',warning:'ಎಚ್ಚರಿಕೆ',openMap:'ಭಾರತದ ಎಚ್ಚರಿಕೆ ನಕ್ಷೆ ತೆರೆಯಿರಿ ↗',rightNow:'ಈಗಲೇ',stepsTitle:'ಪ್ರಯಾಣದಲ್ಲಿ ಸುರಕ್ಷಿತವಾಗಿರಿ',step1Title:'ಜಿಲ್ಲೆ ಮತ್ತು ದಿನಾಂಕ ಪರಿಶೀಲಿಸಿ',step1Text:'ಅಧಿಕೃತ ನಕ್ಷೆಯಲ್ಲಿ ನಿಮ್ಮ ಸ್ಥಳ ಮತ್ತು ಪ್ರಯಾಣದ ದಿನದ ಎಚ್ಚರಿಕೆ ಓದಿ.',step2Title:'ಪ್ರವಾಹದ ನೀರು ಮತ್ತು ತೆರೆದ ಪ್ರದೇಶ ತಪ್ಪಿಸಿ',step2Text:'ಪ್ರವಾಹದ ನೀರಿನಲ್ಲಿ ನಡೆಯಬೇಡಿ ಅಥವಾ ವಾಹನ ಚಲಾಯಿಸಬೇಡಿ. ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳ ಆಶ್ರಯ ಅಥವಾ ಸ್ಥಳಾಂತರ ಸೂಚನೆ ಪಾಲಿಸಿ.',step3Title:'ಹೊರಡುವ ಮುನ್ನ ಮತ್ತೆ ಪರಿಶೀಲಿಸಿ',step3Text:'ಎಚ್ಚರಿಕೆಗಳು ಬದಲಾಗಬಹುದು. ಪ್ರಯಾಣಕ್ಕೂ ಮೊದಲು ಇತ್ತೀಚಿನ ಸ್ಥಳೀಯ ಸೂಚನೆ ಖಚಿತಪಡಿಸಿಕೊಳ್ಳಿ.',nearbyHelp:'ದೇಶವ್ಯಾಪಿ ತುರ್ತು ಸಹಾಯ',helpTitle:'ತುರ್ತು ಪ್ರತಿಕ್ರಿಯೆ',emergencyNumber:'112ಗೆ ಕರೆ ಮಾಡಿ',emergencyDetail:'ಭಾರತದಾದ್ಯಂತ ತುರ್ತು ಸಂಖ್ಯೆ',helpNote:'ಪೊಲೀಸ್, ಅಗ್ನಿಶಾಮಕ, ವೈದ್ಯಕೀಯ ಮತ್ತು ಇತರ ತುರ್ತು ಸಹಾಯಕ್ಕಾಗಿ.',verifyNumbers:'ಅಧಿಕೃತ 112 ಸೇವೆ ↗',infoStatus:'ಮೂಲ ಮತ್ತು ವ್ಯಾಪ್ತಿ',scopeText:'ಎಚ್ಚರಿಕೆಗಳು IMD ಅಧಿಕೃತ ನಕ್ಷೆಯಲ್ಲಿ ತೆರೆಯುತ್ತವೆ; StormSignal ತುರ್ತು ಸೇವೆಯಲ್ಲ.',shareDemo:'ಈ ಪುಟ ಹಂಚಿಕೊಳ್ಳಿ',footer:'ತುರ್ತು ಪರಿಸ್ಥಿತಿಯಲ್ಲಿ 112ಗೆ ಕರೆ ಮಾಡಿ ಮತ್ತು ಸ್ಥಳೀಯ ಅಧಿಕಾರಿಗಳ ಸೂಚನೆ ಪಾಲಿಸಿ.',aboutLabel:'ಈ ಸೇವೆಯ ಕುರಿತು',aboutTitle:'ಸ್ಪಷ್ಟ ಮಾಹಿತಿ. ಸ್ಪಷ್ಟ ಮೂಲ.',aboutBody:'IMD ಸಾರ್ವಜನಿಕ ಜಿಲ್ಲಾ ಎಚ್ಚರಿಕೆ ನಕ್ಷೆಯನ್ನು ತೆರೆಯುವ ಮೂಲಕ StormSignal ಭಾರತಕ್ಕೆ ಮಾಹಿತಿ ನೀಡುತ್ತದೆ. ಅಲ್ಲಿ ಆಯ್ಕೆ ಮಾಡಿದ ಜಿಲ್ಲೆಯ ಅಧಿಕೃತ ಎಚ್ಚರಿಕೆ ಮತ್ತು ದಿನಾಂಕ ದೊರೆಯುತ್ತದೆ. ಈ ಮಾದರಿ ಸ್ಥಳ ಟ್ರ್ಯಾಕಿಂಗ್, ರಸ್ತೆಮಟ್ಟದ ಪರಿಸ್ಥಿತಿ, ಆಶ್ರಯ, ಸ್ಥಳಾಂತರ ಮಾರ್ಗ ಅಥವಾ ರಕ್ಷಣಾ ಸೇವೆ ಒದಗಿಸುವುದಿಲ್ಲ.',gotIt:'ಸರಿ',shareText:'StormSignal ಭಾರತದ ಅಧಿಕೃತ ಜಿಲ್ಲಾ ಹವಾಮಾನ ಎಚ್ಚರಿಕೆ ಮತ್ತು ಪ್ರಯಾಣ ಸುರಕ್ಷತಾ ಮಾರ್ಗದರ್ಶನಕ್ಕೆ ಕೊಂಡಿ ನೀಡುತ್ತದೆ. IMD ನಕ್ಷೆ ನೋಡಿ, ಸ್ಥಳೀಯ ಸೂಚನೆ ಪಾಲಿಸಿ.'},
  ml:{status:'IMD ജില്ല മാപ്പ് · ഇന്ത്യ',languageLabel:'ഭാഷ',eyebrow:'യാത്രാ സുരക്ഷ, വ്യക്തമായി',title:'എന്താണ് സംഭവിക്കുന്നതെന്ന് അറിയുക.<br><em>എന്ത് ചെയ്യണമെന്ന് അറിയുക.</em>',intro:'ഇന്ത്യയിലുടനീളമുള്ള യാത്രക്കാർക്ക് ജില്ലാ കാലാവസ്ഥാ മുന്നറിയിപ്പുകളും പ്രായോഗിക മാർഗനിർദേശവും.',coverageLabel:'പരിധി',coverage:'ഇന്ത്യ · സംസ്ഥാനങ്ങളും കേന്ദ്രഭരണ പ്രദേശങ്ങളും',noticeTitle:'ഔദ്യോഗിക മുന്നറിയിപ്പുകൾ, വ്യക്തമായ അടുത്ത നടപടികൾ',noticeText:'ഇന്ത്യൻ കാലാവസ്ഥാ വകുപ്പിന്റെ സംവേദനാത്മക ജില്ലാ മാപ്പിലേക്ക് StormSignal നിങ്ങളെ നയിക്കുന്നു. അവിടെ ജില്ലയും പ്രവചന തീയതിയും പരിശോധിച്ച് പ്രാദേശിക അധികാരികളുടെ നിർദേശങ്ങൾ പാലിക്കുക.',alertLabel:'ഔദ്യോഗിക ജില്ലാ മുന്നറിയിപ്പുകൾ · ഇന്ത്യ',liveSourceTag:'ഔദ്യോഗിക IMD മാപ്പ്',mapTitle:'നിങ്ങളുടെ ജില്ലയിലെ മുന്നറിയിപ്പ് പരിശോധിക്കുക',mapText:'IMD-യുടെ ഇന്ത്യയിലുടനീളമുള്ള മാപ്പ് തുറന്ന് തീയതി തിരഞ്ഞെടുത്ത് ജില്ലയിലെ മുന്നറിയിപ്പ് വായിക്കുക.',legendTitle:'IMD മുന്നറിയിപ്പ് നിലകൾ',noWarning:'മുന്നറിയിപ്പില്ല',watch:'ശ്രദ്ധിക്കുക',alert:'ജാഗ്രത',warning:'മുന്നറിയിപ്പ്',openMap:'ഇന്ത്യയുടെ മുന്നറിയിപ്പ് മാപ്പ് തുറക്കുക ↗',rightNow:'ഇപ്പോൾ',stepsTitle:'യാത്രയിൽ സുരക്ഷിതരായിരിക്കുക',step1Title:'ജില്ലയും തീയതിയും പരിശോധിക്കുക',step1Text:'ഔദ്യോഗിക മാപ്പിൽ യാത്രാ സ്ഥലത്തിന്റെയും ദിവസത്തിന്റെയും മുന്നറിയിപ്പ് വായിക്കുക.',step2Title:'വെള്ളപ്പൊക്കജലവും തുറന്ന സ്ഥലങ്ങളും ഒഴിവാക്കുക',step2Text:'വെള്ളപ്പൊക്കജലത്തിലൂടെ നടക്കുകയോ വാഹനമോടിക്കുകയോ ചെയ്യരുത്. പ്രാദേശിക അധികാരികളുടെ അഭയ/ഒഴിപ്പിക്കൽ നിർദേശങ്ങൾ പാലിക്കുക.',step3Title:'യാത്ര തുടങ്ങുംമുമ്പ് വീണ്ടും പരിശോധിക്കുക',step3Text:'മുന്നറിയിപ്പുകൾ മാറാം. യാത്രയ്ക്കുമുമ്പ് ഏറ്റവും പുതിയ പ്രാദേശിക നിർദേശങ്ങൾ ഉറപ്പാക്കുക.',nearbyHelp:'രാജ്യവ്യാപക അടിയന്തര സഹായം',helpTitle:'അടിയന്തര പ്രതികരണം',emergencyNumber:'112 വിളിക്കുക',emergencyDetail:'ഇന്ത്യയിലുടനീളമുള്ള അടിയന്തര നമ്പർ',helpNote:'പോലീസ്, അഗ്നിശമനം, വൈദ്യസഹായം, മറ്റ് അടിയന്തര സഹായങ്ങൾക്കായി.',verifyNumbers:'ഔദ്യോഗിക 112 സേവനം ↗',infoStatus:'ഉറവിടവും പരിധിയും',scopeText:'മുന്നറിയിപ്പുകൾ IMD ഔദ്യോഗിക മാപ്പിൽ തുറക്കും; StormSignal അടിയന്തര സേവനമല്ല.',shareDemo:'ഈ പേജ് പങ്കിടുക',footer:'അടിയന്തരാവസ്ഥയിൽ 112 വിളിച്ച് പ്രാദേശിക അധികാരികളുടെ നിർദേശങ്ങൾ പാലിക്കുക.',aboutLabel:'ഈ സേവനത്തെക്കുറിച്ച്',aboutTitle:'വ്യക്തമായ വിവരം. വ്യക്തമായ ഉറവിടം.',aboutBody:'IMD-യുടെ പൊതുജില്ലാ മുന്നറിയിപ്പ് മാപ്പ് തുറന്നാണ് StormSignal ഇന്ത്യയ്ക്കുള്ള വിവരങ്ങൾ നൽകുന്നത്. അവിടെ തിരഞ്ഞെടുക്കുന്ന ജില്ലയുടെ ഔദ്യോഗിക മുന്നറിയിപ്പും തീയതിയും കാണാം. ഈ മാതൃക സ്ഥലനിരീക്ഷണം, റോഡ് നില, അഭയകേന്ദ്രം, ഒഴിപ്പിക്കൽ പാത, രക്ഷാപ്രവർത്തനം എന്നിവ നൽകുന്നില്ല.',gotIt:'ശരി',shareText:'ഇന്ത്യയുടെ ഔദ്യോഗിക ജില്ലാ കാലാവസ്ഥാ മുന്നറിയിപ്പുകളും യാത്രാ സുരക്ഷാ മാർഗനിർദേശങ്ങളും StormSignal നൽകുന്നു. IMD മാപ്പും പ്രാദേശിക നിർദേശങ്ങളും പരിശോധിക്കുക.'},
  pa:{status:'IMD ਜ਼ਿਲ੍ਹਾ ਨਕਸ਼ਾ · ਭਾਰਤ',languageLabel:'ਭਾਸ਼ਾ',eyebrow:'ਯਾਤਰਾ ਸੁਰੱਖਿਆ, ਸਾਫ਼ ਜਾਣਕਾਰੀ',title:'ਜਾਣੋ ਕੀ ਹੋ ਰਿਹਾ ਹੈ।<br><em>ਜਾਣੋ ਕੀ ਕਰਨਾ ਹੈ।</em>',intro:'ਭਾਰਤ ਭਰ ਦੇ ਯਾਤਰੀਆਂ ਲਈ ਜ਼ਿਲ੍ਹਾ ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ ਅਤੇ ਵਰਤੋਂਯੋਗ ਸਲਾਹ।',coverageLabel:'ਦਾਇਰਾ',coverage:'ਭਾਰਤ · ਰਾਜ ਅਤੇ ਕੇਂਦਰ ਸ਼ਾਸਿਤ ਪ੍ਰਦੇਸ਼',noticeTitle:'ਅਧਿਕਾਰਤ ਚੇਤਾਵਨੀਆਂ, ਅਗਲੇ ਕਦਮ ਸਪੱਸ਼ਟ',noticeText:'StormSignal ਤੁਹਾਨੂੰ ਭਾਰਤੀ ਮੌਸਮ ਵਿਭਾਗ ਦੇ ਇੰਟਰਐਕਟਿਵ ਜ਼ਿਲ੍ਹਾ ਨਕਸ਼ੇ ’ਤੇ ਲੈ ਜਾਂਦਾ ਹੈ। ਉੱਥੇ ਜ਼ਿਲ੍ਹਾ ਅਤੇ ਪੇਸ਼ਗੋਈ ਦੀ ਤਾਰੀਖ਼ ਵੇਖੋ ਅਤੇ ਸਥਾਨਕ ਅਧਿਕਾਰੀਆਂ ਦੀਆਂ ਹਦਾਇਤਾਂ ਮੰਨੋ।',alertLabel:'ਅਧਿਕਾਰਤ ਜ਼ਿਲ੍ਹਾ ਚੇਤਾਵਨੀਆਂ · ਭਾਰਤ',liveSourceTag:'ਅਧਿਕਾਰਤ IMD ਨਕਸ਼ਾ',mapTitle:'ਆਪਣੇ ਜ਼ਿਲ੍ਹੇ ਦੀ ਚੇਤਾਵਨੀ ਵੇਖੋ',mapText:'IMD ਦਾ ਦੇਸ਼-ਪੱਧਰੀ ਨਕਸ਼ਾ ਖੋਲ੍ਹੋ, ਤਾਰੀਖ਼ ਚੁਣੋ ਅਤੇ ਆਪਣੇ ਜ਼ਿਲ੍ਹੇ ਦੀ ਚੇਤਾਵਨੀ ਪੜ੍ਹੋ।',legendTitle:'IMD ਚੇਤਾਵਨੀ ਪੱਧਰ',noWarning:'ਚੇਤਾਵਨੀ ਨਹੀਂ',watch:'ਨਜ਼ਰ ਰੱਖੋ',alert:'ਸਾਵਧਾਨ',warning:'ਚੇਤਾਵਨੀ',openMap:'ਭਾਰਤ ਦਾ ਚੇਤਾਵਨੀ ਨਕਸ਼ਾ ਖੋਲ੍ਹੋ ↗',rightNow:'ਹੁਣੇ',stepsTitle:'ਯਾਤਰਾ ਦੌਰਾਨ ਸੁਰੱਖਿਅਤ ਰਹੋ',step1Title:'ਜ਼ਿਲ੍ਹਾ ਅਤੇ ਤਾਰੀਖ਼ ਵੇਖੋ',step1Text:'ਅਧਿਕਾਰਤ ਨਕਸ਼ੇ ’ਤੇ ਯਾਤਰਾ ਵਾਲੀ ਥਾਂ ਅਤੇ ਦਿਨ ਦੀ ਚੇਤਾਵਨੀ ਪੜ੍ਹੋ।',step2Title:'ਹੜ੍ਹ ਦੇ ਪਾਣੀ ਅਤੇ ਖੁੱਲ੍ਹੀਆਂ ਥਾਵਾਂ ਤੋਂ ਬਚੋ',step2Text:'ਹੜ੍ਹ ਦੇ ਪਾਣੀ ਵਿੱਚ ਨਾ ਤੁਰੋ ਅਤੇ ਨਾ ਵਾਹਨ ਚਲਾਓ। ਸਥਾਨਕ ਅਧਿਕਾਰੀਆਂ ਦੀਆਂ ਪਨਾਹ ਜਾਂ ਨਿਕਾਸੀ ਹਦਾਇਤਾਂ ਮੰਨੋ।',step3Title:'ਰਵਾਨਾ ਹੋਣ ਤੋਂ ਪਹਿਲਾਂ ਮੁੜ ਜਾਂਚੋ',step3Text:'ਚੇਤਾਵਨੀਆਂ ਬਦਲ ਸਕਦੀਆਂ ਹਨ। ਯਾਤਰਾ ਤੋਂ ਪਹਿਲਾਂ ਤਾਜ਼ਾ ਸਥਾਨਕ ਹਦਾਇਤਾਂ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।',nearbyHelp:'ਦੇਸ਼-ਪੱਧਰੀ ਐਮਰਜੈਂਸੀ ਮਦਦ',helpTitle:'ਐਮਰਜੈਂਸੀ ਸਹਾਇਤਾ',emergencyNumber:'112 ’ਤੇ ਕਾਲ ਕਰੋ',emergencyDetail:'ਪੂਰੇ ਭਾਰਤ ਦਾ ਐਮਰਜੈਂਸੀ ਨੰਬਰ',helpNote:'ਪੁਲਿਸ, ਅੱਗ ਬੁਝਾਊ, ਡਾਕਟਰੀ ਅਤੇ ਹੋਰ ਐਮਰਜੈਂਸੀ ਮਦਦ ਲਈ।',verifyNumbers:'ਅਧਿਕਾਰਤ 112 ਸੇਵਾ ↗',infoStatus:'ਸਰੋਤ ਅਤੇ ਦਾਇਰਾ',scopeText:'ਚੇਤਾਵਨੀਆਂ IMD ਦੇ ਅਧਿਕਾਰਤ ਨਕਸ਼ੇ ’ਤੇ ਖੁੱਲ੍ਹਦੀਆਂ ਹਨ; StormSignal ਐਮਰਜੈਂਸੀ ਸੇਵਾ ਨਹੀਂ ਹੈ।',shareDemo:'ਇਹ ਪੰਨਾ ਸਾਂਝਾ ਕਰੋ',footer:'ਐਮਰਜੈਂਸੀ ਵਿੱਚ 112 ’ਤੇ ਕਾਲ ਕਰੋ ਅਤੇ ਸਥਾਨਕ ਹਦਾਇਤਾਂ ਮੰਨੋ।',aboutLabel:'ਇਸ ਸੇਵਾ ਬਾਰੇ',aboutTitle:'ਸਪੱਸ਼ਟ ਜਾਣਕਾਰੀ। ਸਪੱਸ਼ਟ ਸਰੋਤ।',aboutBody:'StormSignal IMD ਦਾ ਜਨਤਕ ਜ਼ਿਲ੍ਹਾ ਚੇਤਾਵਨੀ ਨਕਸ਼ਾ ਖੋਲ੍ਹ ਕੇ ਭਾਰਤ ਭਰ ਦੀ ਜਾਣਕਾਰੀ ਦਿੰਦਾ ਹੈ। ਚੁਣੇ ਜ਼ਿਲ੍ਹੇ ਦੀ ਅਧਿਕਾਰਤ ਚੇਤਾਵਨੀ ਅਤੇ ਤਾਰੀਖ਼ ਉੱਥੇ ਵੇਖੋ। ਇਹ ਨਮੂਨਾ ਟਿਕਾਣਾ ਟ੍ਰੈਕਿੰਗ, ਸੜਕ ਦੀ ਸਥਿਤੀ, ਪਨਾਹ, ਨਿਕਾਸੀ ਰਸਤੇ ਜਾਂ ਬਚਾਅ ਸੇਵਾ ਨਹੀਂ ਦਿੰਦਾ।',gotIt:'ਠੀਕ ਹੈ',shareText:'StormSignal ਭਾਰਤ ਦੀਆਂ ਅਧਿਕਾਰਤ ਜ਼ਿਲ੍ਹਾ ਮੌਸਮ ਚੇਤਾਵਨੀਆਂ ਅਤੇ ਯਾਤਰਾ ਸੁਰੱਖਿਆ ਸਲਾਹ ਨਾਲ ਜੋੜਦਾ ਹੈ। IMD ਨਕਸ਼ਾ ਵੇਖੋ ਅਤੇ ਸਥਾਨਕ ਹਦਾਇਤਾਂ ਮੰਨੋ।'},
  or:{status:'IMD ଜିଲ୍ଲା ମାନଚିତ୍ର · ଭାରତ',languageLabel:'ଭାଷା',eyebrow:'ଯାତ୍ରା ସୁରକ୍ଷା, ସ୍ପଷ୍ଟ ସୂଚନା',title:'କ’ଣ ଘଟୁଛି ଜାଣନ୍ତୁ।<br><em>କ’ଣ କରିବେ ଜାଣନ୍ତୁ।</em>',intro:'ଭାରତର ଯାତ୍ରୀଙ୍କ ପାଇଁ ଜିଲ୍ଲା ପାଣିପାଗ ସତର୍କତା ଓ ବ୍ୟବହାରିକ ପରାମର୍ଶ।',coverageLabel:'ପରିସର',coverage:'ଭାରତ · ରାଜ୍ୟ ଓ କେନ୍ଦ୍ରଶାସିତ ଅଞ୍ଚଳ',noticeTitle:'ସରକାରୀ ସତର୍କତା, ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ ସ୍ପଷ୍ଟ',noticeText:'StormSignal ଆପଣଙ୍କୁ ଭାରତୀୟ ପାଣିପାଗ ବିଭାଗର ଇଣ୍ଟର୍‌ଆକ୍ଟିଭ୍ ଜିଲ୍ଲା ମାନଚିତ୍ରକୁ ନେଇଯାଏ। ସେଠାରେ ଜିଲ୍ଲା ଓ ପୂର୍ବାନୁମାନ ତାରିଖ ଦେଖି ସ୍ଥାନୀୟ ଅଧିକାରୀଙ୍କ ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।',alertLabel:'ସରକାରୀ ଜିଲ୍ଲା ସତର୍କତା · ଭାରତ',liveSourceTag:'ସରକାରୀ IMD ମାନଚିତ୍ର',mapTitle:'ଆପଣଙ୍କ ଜିଲ୍ଲାର ସତର୍କତା ଦେଖନ୍ତୁ',mapText:'IMDର ସାରା ଭାରତ ମାନଚିତ୍ର ଖୋଲନ୍ତୁ, ତାରିଖ ବାଛନ୍ତୁ ଓ ଜିଲ୍ଲା ସତର୍କତା ପଢ଼ନ୍ତୁ।',legendTitle:'IMD ସତର୍କତା ସ୍ତର',noWarning:'ସତର୍କତା ନାହିଁ',watch:'ନଜର ରଖନ୍ତୁ',alert:'ସତର୍କ',warning:'ସତର୍କତା',openMap:'ଭାରତ ସତର୍କତା ମାନଚିତ୍ର ଖୋଲନ୍ତୁ ↗',rightNow:'ଏବେ',stepsTitle:'ଯାତ୍ରାରେ ସୁରକ୍ଷିତ ରୁହନ୍ତୁ',step1Title:'ଜିଲ୍ଲା ଓ ତାରିଖ ଯାଞ୍ଚ କରନ୍ତୁ',step1Text:'ସରକାରୀ ମାନଚିତ୍ରରେ ଯାତ୍ରା ସ୍ଥାନ ଓ ଦିନର ସତର୍କତା ପଢ଼ନ୍ତୁ।',step2Title:'ବନ୍ୟା ଜଳ ଓ ଖୋଲା ସ୍ଥାନରୁ ଦୂରେ ରୁହନ୍ତୁ',step2Text:'ବନ୍ୟା ଜଳରେ ଚାଲନ୍ତୁ ନାହିଁ କିମ୍ବା ଗାଡ଼ି ଚଳାନ୍ତୁ ନାହିଁ। ସ୍ଥାନୀୟ ଅଧିକାରୀଙ୍କ ଆଶ୍ରୟ ବା ସ୍ଥାନାନ୍ତର ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।',step3Title:'ଯିବା ପୂର୍ବରୁ ପୁଣି ଯାଞ୍ଚ କରନ୍ତୁ',step3Text:'ସତର୍କତା ବଦଳିପାରେ। ଯାତ୍ରା ପୂର୍ବରୁ ସାମ୍ପ୍ରତିକ ସ୍ଥାନୀୟ ନିର୍ଦ୍ଦେଶ ନିଶ୍ଚିତ କରନ୍ତୁ।',nearbyHelp:'ସାରା ଦେଶର ଜରୁରୀ ସହାୟତା',helpTitle:'ଜରୁରୀ ସହାୟତା',emergencyNumber:'112କୁ କଲ୍ କରନ୍ତୁ',emergencyDetail:'ସାରା ଭାରତର ଜରୁରୀ ନମ୍ବର',helpNote:'ପୋଲିସ, ଅଗ୍ନିଶମ, ଚିକିତ୍ସା ଓ ଅନ୍ୟ ଜରୁରୀ ସହାୟତା ପାଇଁ।',verifyNumbers:'ସରକାରୀ 112 ସେବା ↗',infoStatus:'ଉତ୍ସ ଓ ପରିସର',scopeText:'ସତର୍କତା IMDର ସରକାରୀ ମାନଚିତ୍ରରେ ଖୋଲିବ; StormSignal ଜରୁରୀ ସେବା ନୁହେଁ।',shareDemo:'ଏହି ପୃଷ୍ଠା ସେୟାର କରନ୍ତୁ',footer:'ଜରୁରୀ ସମୟରେ 112କୁ କଲ୍ କରି ସ୍ଥାନୀୟ ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।',aboutLabel:'ଏହି ସେବା ବିଷୟରେ',aboutTitle:'ସ୍ପଷ୍ଟ ସୂଚନା। ସ୍ପଷ୍ଟ ଉତ୍ସ।',aboutBody:'IMDର ସାର୍ବଜନୀନ ଜିଲ୍ଲା ସତର୍କତା ମାନଚିତ୍ର ଖୋଲି StormSignal ଭାରତ ପାଇଁ ସୂଚନା ଦିଏ। ସେଠାରେ ଚୟନ କରାଯାଇଥିବା ଜିଲ୍ଲାର ସରକାରୀ ସତର୍କତା ଓ ତାରିଖ ଦେଖନ୍ତୁ। ଏହି ନମୁନା ଅବସ୍ଥାନ ଟ୍ରାକିଂ, ରାସ୍ତା ସ୍ଥିତି, ଆଶ୍ରୟ, ସ୍ଥାନାନ୍ତର ପଥ ବା ଉଦ୍ଧାର ସେବା ଦିଏ ନାହିଁ।',gotIt:'ଠିକ୍ ଅଛି',shareText:'StormSignal ଭାରତର ସରକାରୀ ଜିଲ୍ଲା ପାଣିପାଗ ସତର୍କତା ଓ ଯାତ୍ରା ସୁରକ୍ଷା ପରାମର୍ଶ ସହ ଯୋଡ଼େ। IMD ମାନଚିତ୍ର ଦେଖନ୍ତୁ ଓ ସ୍ଥାନୀୟ ନିର୍ଦ୍ଦେଶ ମାନନ୍ତୁ।'},
  as:{status:'IMD জিলা মানচিত্ৰ · ভাৰত',languageLabel:'ভাষা',eyebrow:'ভ্ৰমণ সুৰক্ষা, স্পষ্টভাৱে',title:'কি ঘটিছে জানক।<br><em>কি কৰিব লাগে জানক।</em>',intro:'ভাৰতৰ সকলো ঠাইৰ ভ্ৰমণকাৰীৰ বাবে জিলা বতৰৰ সতৰ্কবাণী আৰু ব্যৱহাৰিক পৰামৰ্শ।',coverageLabel:'সামৰি লোৱা অঞ্চল',coverage:'ভাৰত · ৰাজ্য আৰু কেন্দ্ৰীয় শাসিত অঞ্চল',noticeTitle:'চৰকাৰী সতৰ্কবাণী, পৰৱৰ্তী পদক্ষেপ স্পষ্ট',noticeText:'StormSignal-এ আপোনাক ভাৰতীয় বতৰ বিজ্ঞান বিভাগৰ ইণ্টাৰেক্টিভ জিলা মানচিত্ৰলৈ লৈ যায়। তাত জিলা আৰু পূৰ্বানুমানৰ তাৰিখ চাই স্থানীয় কৰ্তৃপক্ষৰ নিৰ্দেশ মানক।',alertLabel:'চৰকাৰী জিলা সতৰ্কবাণী · ভাৰত',liveSourceTag:'চৰকাৰী IMD মানচিত্ৰ',mapTitle:'আপোনাৰ জিলাৰ সতৰ্কবাণী চাওক',mapText:'IMD-ৰ দেশজোৰা মানচিত্ৰ খুলি তাৰিখ বাছনি কৰি জিলাৰ সতৰ্কবাণী পঢ়ক।',legendTitle:'IMD সতৰ্কবাণীৰ স্তৰ',noWarning:'সতৰ্কবাণী নাই',watch:'মন কৰক',alert:'সতৰ্ক হওক',warning:'সতৰ্কবাণী',openMap:'ভাৰতৰ সতৰ্কবাণী মানচিত্ৰ খোলক ↗',rightNow:'এতিয়াই',stepsTitle:'ভ্ৰমণত সুৰক্ষিত থাকক',step1Title:'জিলা আৰু তাৰিখ পৰীক্ষা কৰক',step1Text:'চৰকাৰী মানচিত্ৰত ভ্ৰমণৰ ঠাই আৰু দিনৰ সতৰ্কবাণী পঢ়ক।',step2Title:'বানপানী আৰু মুকলি ঠাই এৰাই চলক',step2Text:'বানপানীৰ মাজেৰে খোজ কাঢ়ি বা গাড়ী চলাই নাযাব। স্থানীয় কৰ্তৃপক্ষৰ আশ্ৰয় বা স্থানান্তৰৰ নিৰ্দেশ মানক।',step3Title:'যাত্ৰা কৰাৰ আগতে পুনৰ চাওক',step3Text:'সতৰ্কবাণী সলনি হ’ব পাৰে। যাত্ৰাৰ আগতে শেহতীয়া স্থানীয় নিৰ্দেশ নিশ্চিত কৰক।',nearbyHelp:'সৰ্বভাৰতীয় জৰুৰী সহায়',helpTitle:'জৰুৰীকালীন সহায়',emergencyNumber:'112-লৈ ফোন কৰক',emergencyDetail:'গোটেই ভাৰতৰ জৰুৰী নম্বৰ',helpNote:'আৰক্ষী, অগ্নিনিৰ্বাপক, চিকিৎসা আৰু আন জৰুৰী সহায়ৰ বাবে।',verifyNumbers:'চৰকাৰী 112 সেৱা ↗',infoStatus:'উৎস আৰু পৰিসৰ',scopeText:'সতৰ্কবাণী IMD-ৰ চৰকাৰী মানচিত্ৰত খোল খায়; StormSignal জৰুৰী সেৱা নহয়।',shareDemo:'এই পৃষ্ঠা ভাগ কৰক',footer:'জৰুৰী অৱস্থাত 112-লৈ ফোন কৰি স্থানীয় নিৰ্দেশ মানক।',aboutLabel:'এই সেৱাৰ বিষয়ে',aboutTitle:'স্পষ্ট তথ্য। স্পষ্ট উৎস।',aboutBody:'IMD-ৰ ৰাজহুৱা জিলা সতৰ্কবাণীৰ মানচিত্ৰ খুলি StormSignal-এ ভাৰতৰ তথ্য দেখুৱায়। তাত বাছনি কৰা জিলাৰ চৰকাৰী সতৰ্কবাণী আৰু তাৰিখ পোৱা যায়। এই আৰ্হিয়ে অৱস্থান অনুসৰণ, পথৰ অৱস্থা, আশ্ৰয়, স্থানান্তৰৰ পথ বা উদ্ধাৰ সেৱা নিদিয়ে।',gotIt:'ঠিক আছে',shareText:'StormSignal-এ ভাৰতৰ চৰকাৰী জিলা বতৰৰ সতৰ্কবাণী আৰু ভ্ৰমণ সুৰক্ষাৰ পৰামৰ্শলৈ লৈ যায়। IMD মানচিত্ৰ চাওক আৰু স্থানীয় নিৰ্দেশ মানক।'},
  ur:{status:'IMD ضلعی نقشہ · بھارت',languageLabel:'زبان',eyebrow:'سفر کی حفاظت، واضح معلومات',title:'جانیں کیا ہو رہا ہے۔<br><em>جانیں کیا کرنا ہے۔</em>',intro:'بھارت بھر کے مسافروں کے لیے ضلعی موسم کی تنبیہات اور عملی رہنمائی۔',coverageLabel:'دائرہ',coverage:'بھارت · ریاستیں اور مرکز کے زیر انتظام علاقے',noticeTitle:'سرکاری تنبیہات، اگلے اقدامات واضح',noticeText:'StormSignal آپ کو محکمہ موسمیات کے انٹرایکٹو ضلعی نقشے تک لے جاتا ہے۔ وہاں ضلع اور پیش گوئی کی تاریخ دیکھیں اور مقامی حکام کی ہدایات پر عمل کریں۔',alertLabel:'سرکاری ضلعی تنبیہات · بھارت',liveSourceTag:'سرکاری IMD نقشہ',mapTitle:'اپنے ضلع کی تنبیہ دیکھیں',mapText:'IMD کا ملک گیر نقشہ کھولیں، تاریخ منتخب کریں اور اپنے ضلع کی تنبیہ پڑھیں۔',legendTitle:'IMD تنبیہ کی سطحیں',noWarning:'کوئی تنبیہ نہیں',watch:'نظر رکھیں',alert:'خبردار',warning:'تنبیہ',openMap:'بھارت کا تنبیہی نقشہ کھولیں ↗',rightNow:'ابھی',stepsTitle:'سفر میں محفوظ رہیں',step1Title:'ضلع اور تاریخ دیکھیں',step1Text:'سرکاری نقشے پر سفر کی جگہ اور دن کی تنبیہ پڑھیں۔',step2Title:'سیلابی پانی اور کھلی جگہوں سے بچیں',step2Text:'سیلابی پانی میں نہ چلیں اور نہ گاڑی چلائیں۔ مقامی حکام کی پناہ یا انخلا کی ہدایات پر عمل کریں۔',step3Title:'روانہ ہونے سے پہلے دوبارہ دیکھیں',step3Text:'تنبیہات بدل سکتی ہیں۔ سفر سے پہلے تازہ مقامی ہدایات کی تصدیق کریں۔',nearbyHelp:'ملک گیر ہنگامی مدد',helpTitle:'ہنگامی امداد',emergencyNumber:'112 پر کال کریں',emergencyDetail:'پورے بھارت کا ہنگامی نمبر',helpNote:'پولیس، فائر، طبی اور دیگر ہنگامی مدد کے لیے۔',verifyNumbers:'سرکاری 112 سروس ↗',infoStatus:'ماخذ اور دائرہ',scopeText:'تنبیہات IMD کے سرکاری نقشے پر کھلتی ہیں؛ StormSignal ہنگامی سروس نہیں۔',shareDemo:'یہ صفحہ شیئر کریں',footer:'ہنگامی حالت میں 112 پر کال کریں اور مقامی حکام کی ہدایات پر عمل کریں۔',aboutLabel:'اس سروس کے بارے میں',aboutTitle:'واضح معلومات۔ واضح ماخذ۔',aboutBody:'StormSignal، IMD کے عوامی ضلعی تنبیہی نقشے کے ذریعے بھارت بھر کی معلومات دکھاتا ہے۔ منتخب ضلع کی سرکاری تنبیہ اور تاریخ نقشے پر دیکھیں۔ یہ نمونہ مقام کی نگرانی، سڑک کی حالت، پناہ گاہ، انخلا کے راستے یا امدادی کارروائی فراہم نہیں کرتا۔',gotIt:'ٹھیک ہے',shareText:'StormSignal بھارت کی سرکاری ضلعی موسم کی تنبیہات اور سفری حفاظتی رہنمائی سے جوڑتا ہے۔ IMD نقشہ دیکھیں اور مقامی ہدایات پر عمل کریں۔'}
};

// Practical interface translations for international visitors. IMD alerts remain
// on the official source page and are not rewritten by StormSignal.
Object.assign(translated,{
  fr:{status:'Alertes IMD par district · Inde',sourceName:'India Meteorological Department',sourceDetail:'Alertes officielles par district en Inde · dates de prévision sur IMD',aboutLink:'Comment ça marche',languageLabel:'Langue',installApp:'Installer l’application',eyebrow:'LA SÉCURITÉ EN VOYAGE, EN CLAIR',title:'Comprendre la situation.<br><em>Savoir quoi faire.</em>',intro:'Alertes météo par district et conseils pratiques pour les voyageurs en Inde.',coverageLabel:'ZONE COUVERTE',coverage:'Inde · États et territoires de l’Union',noticeTitle:'Alertes officielles, prochaines étapes claires',noticeText:'StormSignal vous dirige vers la carte interactive des alertes par district du service météorologique indien. Vérifiez le district et la date de prévision, puis suivez les consignes locales.',alertLabel:'ALERTES OFFICIELLES PAR DISTRICT · INDE',liveSourceTag:'CARTE IMD OFFICIELLE',mapTitle:'Consultez l’alerte de votre district',mapText:'Ouvrez la carte nationale de l’IMD, choisissez une date de prévision et sélectionnez votre district pour lire son alerte.',legendTitle:'Niveaux d’alerte IMD',noWarning:'Aucune alerte',watch:'Veille',alert:'Alerte',warning:'Avertissement',openMap:'Ouvrir la carte des alertes ↗',rightNow:'À RETENIR',stepsTitle:'Voyagez plus prudemment',step1Title:'Vérifiez votre district et la date',step1Text:'Lisez l’alerte officielle pour votre destination et le jour de votre voyage.',step2Title:'Évitez l’eau de crue et les zones exposées',step2Text:'Ne marchez pas et ne conduisez jamais dans l’eau de crue. Suivez les consignes d’abri ou d’évacuation des autorités locales.',step3Title:'Vérifiez de nouveau avant de partir',step3Text:'Les alertes peuvent changer. Confirmez les dernières consignes locales avant de voyager.',nearbyHelp:'AIDE D’URGENCE DANS TOUTE L’INDE',helpTitle:'Services d’urgence',emergencyNumber:'Appelez le 112',emergencyDetail:'Numéro d’urgence dans toute l’Inde',helpNote:'Pour la police, les pompiers, les soins médicaux et les autres urgences.',verifyNumbers:'Service officiel 112 ↗',infoStatus:'Source et limites',scopeText:'Les alertes s’ouvrent sur la carte officielle de l’IMD. StormSignal n’est pas un service d’urgence.',shareDemo:'Partager cette page',footer:'En cas d’urgence, appelez le 112 et suivez les consignes locales.',aboutLabel:'À PROPOS DE CE SERVICE',aboutTitle:'Des informations claires. Une source claire.',aboutBody:'StormSignal renvoie vers la carte publique de l’IMD pour consulter les alertes par district en Inde. Les alertes officielles restent sur le site source. Les conseils traduits sont une aide concise, pas une traduction officielle des alertes. Cette version ne fournit pas le suivi de localisation, l’état des rues, les abris vérifiés, les itinéraires d’évacuation ni les secours.',gotIt:'Compris',shareText:'StormSignal aide les voyageurs à trouver les alertes météo officielles par district en Inde et des conseils de sécurité. Consultez la carte de l’IMD et suivez les consignes locales.'},
  es:{status:'Alertas del IMD por distrito · India',sourceName:'India Meteorological Department',sourceDetail:'Alertas oficiales por distrito en India · fechas de pronóstico en el IMD',aboutLink:'Cómo funciona',languageLabel:'Idioma',installApp:'Instalar app',eyebrow:'SEGURIDAD PARA VIAJAR, CON CLARIDAD',title:'Entérate de lo que ocurre.<br><em>Y de qué hacer.</em>',intro:'Alertas meteorológicas por distrito y consejos prácticos para viajeros en India.',coverageLabel:'COBERTURA',coverage:'India · estados y territorios de la Unión',noticeTitle:'Alertas oficiales y próximos pasos claros',noticeText:'StormSignal te lleva al mapa interactivo de alertas por distrito del Departamento Meteorológico de India. Comprueba el distrito y la fecha del pronóstico, y sigue las indicaciones locales.',alertLabel:'ALERTAS OFICIALES POR DISTRITO · INDIA',liveSourceTag:'MAPA OFICIAL DEL IMD',mapTitle:'Consulta la alerta de tu distrito',mapText:'Abre el mapa nacional del IMD, elige una fecha del pronóstico y selecciona tu distrito para leer la alerta.',legendTitle:'Niveles de alerta del IMD',noWarning:'Sin aviso',watch:'Vigilancia',alert:'Alerta',warning:'Aviso',openMap:'Abrir mapa de alertas de India ↗',rightNow:'AHORA',stepsTitle:'Viaja con más seguridad',step1Title:'Comprueba el distrito y la fecha',step1Text:'Lee la alerta oficial para tu destino y el día de tu viaje.',step2Title:'Evita el agua de inundación y las zonas expuestas',step2Text:'Nunca camines ni conduzcas por agua de inundación. Sigue las instrucciones locales de refugio o evacuación.',step3Title:'Vuelve a comprobarlo antes de salir',step3Text:'Las alertas pueden cambiar. Confirma las últimas indicaciones locales antes de viajar.',nearbyHelp:'AYUDA DE EMERGENCIA EN TODA INDIA',helpTitle:'Emergencias',emergencyNumber:'Llama al 112',emergencyDetail:'Número de emergencias en toda India',helpNote:'Para policía, bomberos, atención médica y otras emergencias.',verifyNumbers:'Servicio oficial 112 ↗',infoStatus:'Fuente y alcance',scopeText:'Las alertas se abren en el mapa oficial del IMD. StormSignal no es un servicio de emergencia.',shareDemo:'Compartir esta página',footer:'En una emergencia, llama al 112 y sigue las indicaciones locales.',aboutLabel:'SOBRE ESTE SERVICIO',aboutTitle:'Información clara. Fuente clara.',aboutBody:'StormSignal enlaza con el mapa público del IMD para consultar alertas por distrito en India. Las alertas oficiales permanecen en la fuente original. Los consejos traducidos son una ayuda breve, no una traducción oficial de las alertas. Esta versión no ofrece seguimiento de ubicación, estado de calles, refugios verificados, rutas de evacuación ni rescate.',gotIt:'Entendido',shareText:'StormSignal ayuda a los viajeros a encontrar alertas meteorológicas oficiales por distrito en India y consejos de seguridad. Consulta el mapa del IMD y sigue las indicaciones locales.'},
  de:{status:'IMD-Warnungen nach Bezirk · Indien',sourceName:'India Meteorological Department',sourceDetail:'Offizielle Bezirkswarnungen für Indien · Vorhersagedaten beim IMD',aboutLink:'So funktioniert es',languageLabel:'Sprache',installApp:'App installieren',eyebrow:'REISESICHERHEIT, KLAR ERKLÄRT',title:'Erfahren, was passiert.<br><em>Wissen, was zu tun ist.</em>',intro:'Wetterwarnungen nach Bezirk und praktische Hinweise für Reisende in Indien.',coverageLabel:'ABDECKUNG',coverage:'Indien · Bundesstaaten und Unionsterritorien',noticeTitle:'Offizielle Warnungen, klare nächste Schritte',noticeText:'StormSignal führt zur interaktiven Bezirkswarnkarte des indischen Wetterdienstes. Prüfe dort Bezirk und Vorhersagedatum und befolge die aktuellen Anweisungen der örtlichen Behörden.',alertLabel:'OFFIZIELLE BEZIRKSWARNUNGEN · INDIEN',liveSourceTag:'OFFIZIELLE IMD-KARTE',mapTitle:'Warnung für deinen Bezirk ansehen',mapText:'Öffne die landesweite IMD-Karte, wähle ein Vorhersagedatum und deinen Bezirk aus.',legendTitle:'IMD-Warnstufen',noWarning:'Keine Warnung',watch:'Beobachtung',alert:'Alarm',warning:'Warnung',openMap:'Indien-Warnkarte öffnen ↗',rightNow:'JETZT',stepsTitle:'Sicherer unterwegs',step1Title:'Bezirk und Datum prüfen',step1Text:'Lies die offizielle Warnung für dein Reiseziel und den Reisetag.',step2Title:'Hochwasser und ungeschützte Orte meiden',step2Text:'Gehe und fahre niemals durch Hochwasser. Befolge die örtlichen Anweisungen zu Schutz und Evakuierung.',step3Title:'Vor der Abfahrt erneut prüfen',step3Text:'Warnungen können sich ändern. Prüfe vor der Reise die neuesten örtlichen Anweisungen.',nearbyHelp:'NOTFALLHILFE IN GANZ INDIEN',helpTitle:'Notfallhilfe',emergencyNumber:'112 anrufen',emergencyDetail:'Notrufnummer in ganz Indien',helpNote:'Für Polizei, Feuerwehr, medizinische und andere Notfälle.',verifyNumbers:'Offizieller 112-Dienst ↗',infoStatus:'Quelle und Umfang',scopeText:'Warnungen werden auf der offiziellen IMD-Karte geöffnet. StormSignal ist kein Notfalldienst.',shareDemo:'Seite teilen',footer:'Im Notfall 112 anrufen und den örtlichen Anweisungen folgen.',aboutLabel:'ÜBER DIESEN DIENST',aboutTitle:'Klare Informationen. Klare Quelle.',aboutBody:'StormSignal verlinkt die öffentliche IMD-Karte mit den Bezirkswarnungen für Indien. Offizielle Warnungen bleiben auf der Quellseite. Übersetzte Hinweise sind eine kurze Hilfe, keine offizielle Übersetzung der Warnungen. Diese Version bietet keine Standortverfolgung, Straßenlage, bestätigten Schutzräume, Evakuierungsrouten oder Rettungsdienste.',gotIt:'Verstanden',shareText:'StormSignal hilft Reisenden, offizielle Wetterwarnungen nach Bezirk in Indien und praktische Sicherheitshinweise zu finden. Prüfe die IMD-Karte und befolge die örtlichen Anweisungen.'},
  zh:{status:'印度气象局 · 印度地区预警',sourceName:'India Meteorological Department',sourceDetail:'印度各地区官方预警 · 预报日期以印度气象局为准',aboutLink:'使用说明',languageLabel:'语言',installApp:'安装应用',eyebrow:'清晰了解旅途安全',title:'了解正在发生什么。<br><em>知道该怎么做。</em>',intro:'为印度旅行者提供地区天气预警入口和实用安全建议。',coverageLabel:'覆盖范围',coverage:'印度 · 各邦和中央直辖区',noticeTitle:'官方预警，清楚的下一步',noticeText:'StormSignal 将你带到印度气象局的地区预警互动地图。请在那里核对地区和预报日期，并遵循当地主管部门的最新指引。',alertLabel:'印度地区官方预警',liveSourceTag:'印度气象局官方地图',mapTitle:'查看所在地区的预警',mapText:'打开印度气象局全国地图，选择预报日期和地区查看预警。',legendTitle:'印度气象局预警级别',noWarning:'无预警',watch:'关注',alert:'警戒',warning:'预警',openMap:'打开印度预警地图 ↗',rightNow:'安全提示',stepsTitle:'让旅途更安全',step1Title:'核对地区和日期',step1Text:'查看目的地和出行日期对应的官方预警。',step2Title:'远离洪水和无遮蔽区域',step2Text:'切勿步行或驾车穿越洪水。遵循当地主管部门关于避险或撤离的指引。',step3Title:'出发前再次确认',step3Text:'预警可能变化。出行前请再次确认当地最新指引。',nearbyHelp:'印度全国紧急援助',helpTitle:'紧急援助',emergencyNumber:'拨打 112',emergencyDetail:'印度全国紧急电话号码',helpNote:'适用于警务、消防、医疗及其他紧急援助。',verifyNumbers:'印度官方 112 服务 ↗',infoStatus:'信息来源与范围',scopeText:'预警在印度气象局官方地图中查看。StormSignal 不是紧急救援服务。',shareDemo:'分享此页面',footer:'遇到紧急情况请拨打 112，并遵循当地主管部门指引。',aboutLabel:'关于本服务',aboutTitle:'信息清晰，来源明确。',aboutBody:'StormSignal 链接到印度气象局公开的地区预警地图。官方预警保留在来源页面；这里的翻译建议仅供参考，并非官方预警翻译。本版本不提供自动定位、道路状况、已核实避难所、撤离路线或救援调度。',gotIt:'知道了',shareText:'StormSignal 帮助旅行者查找印度官方地区天气预警和实用安全建议。请查看印度气象局地图并遵循当地指引。'},
  ja:{status:'インド気象局 · インドの地区別警報',sourceName:'India Meteorological Department',sourceDetail:'インド全土の公式な地区別警報 · 予報日はIMDで確認',aboutLink:'利用方法',languageLabel:'言語',installApp:'アプリをインストール',eyebrow:'旅行の安全情報をわかりやすく',title:'状況を知る。<br><em>取るべき行動を知る。</em>',intro:'インドを旅行する方向けの地区別気象警報と実用的な安全案内です。',coverageLabel:'対象地域',coverage:'インド · 州および連邦直轄領',noticeTitle:'公式警報と次の行動をわかりやすく',noticeText:'StormSignalはインド気象局の地区別警報マップを開きます。そこで地区と予報日を確認し、現地当局の最新指示に従ってください。',alertLabel:'インド全土の公式地区別警報',liveSourceTag:'IMD公式マップ',mapTitle:'地区の警報を確認する',mapText:'IMDの全国マップを開き、予報日と地区を選んで警報を確認してください。',legendTitle:'IMD警報レベル',noWarning:'警報なし',watch:'注意',alert:'警戒',warning:'警報',openMap:'インドの警報マップを開く ↗',rightNow:'安全のために',stepsTitle:'旅行中の安全を守る',step1Title:'地区と日付を確認する',step1Text:'旅行先と旅行日に対応する公式警報を確認してください。',step2Title:'洪水の水や危険な場所を避ける',step2Text:'洪水の中を歩いたり運転したりしないでください。避難や安全確保に関する現地当局の指示に従ってください。',step3Title:'出発前にもう一度確認する',step3Text:'警報は変わることがあります。出発前に現地の最新指示を確認してください。',nearbyHelp:'インド全土の緊急連絡',helpTitle:'緊急時の支援',emergencyNumber:'112に電話',emergencyDetail:'インド全土の緊急電話番号',helpNote:'警察、消防、医療などの緊急支援に利用できます。',verifyNumbers:'インド政府の112サービス ↗',infoStatus:'情報源と対象範囲',scopeText:'警報はIMDの公式マップで確認します。StormSignalは緊急サービスではありません。',shareDemo:'このページを共有',footer:'緊急時は112に電話し、現地当局の指示に従ってください。',aboutLabel:'このサービスについて',aboutTitle:'明確な情報。明確な情報源。',aboutBody:'StormSignalはIMDの公開地区別警報マップを案内します。公式警報は情報源のページに表示されます。翻訳された案内は参考情報であり、公式な警報翻訳ではありません。この版では位置追跡、道路状況、確認済み避難所、避難経路、救助要請は提供しません。',gotIt:'確認',shareText:'StormSignalは、インドの公式な地区別気象警報と旅行中の安全案内を確認するための入口です。IMDのマップと現地当局の指示を確認してください。'}
});

const sourceLabels={
  hi:['यह कैसे काम करता है','पूरे भारत की आधिकारिक जिला चेतावनियाँ · IMD पर पूर्वानुमान की तारीखें'],
  ta:['இது எப்படி செயல்படுகிறது','இந்தியா முழுவதும் அதிகாரப்பூர்வ மாவட்ட எச்சரிக்கைகள் · IMD-யில் முன்னறிவிப்பு நாட்கள்'],
  te:['ఇది ఎలా పనిచేస్తుంది','భారతదేశమంతటా అధికారిక జిల్లా హెచ్చరికలు · IMDలో సూచన తేదీలు'],
  bn:['এটি কীভাবে কাজ করে','ভারতজুড়ে সরকারি জেলা সতর্কতা · IMD-তে পূর্বাভাসের তারিখ'],
  mr:['हे कसे काम करते','भारतभरातील अधिकृत जिल्हा इशारे · IMD वर अंदाजाच्या तारखा'],
  gu:['આ કેવી રીતે કાર્ય કરે છે','ભારતભરની સત્તાવાર જિલ્લા ચેતવણીઓ · IMD પર આગાહીની તારીખો'],
  kn:['ಇದು ಹೇಗೆ ಕೆಲಸ ಮಾಡುತ್ತದೆ','ಭಾರತದಾದ್ಯಂತ ಅಧಿಕೃತ ಜಿಲ್ಲಾ ಎಚ್ಚರಿಕೆಗಳು · IMDಯಲ್ಲಿ ಮುನ್ಸೂಚನೆ ದಿನಾಂಕಗಳು'],
  ml:['ഇത് എങ്ങനെ പ്രവർത്തിക്കുന്നു','ഇന്ത്യയിലുടനീളമുള്ള ഔദ്യോഗിക ജില്ലാ മുന്നറിയിപ്പുകൾ · IMD-യിലെ പ്രവചന തീയതികൾ'],
  pa:['ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ','ਭਾਰਤ ਭਰ ਦੀਆਂ ਅਧਿਕਾਰਤ ਜ਼ਿਲ੍ਹਾ ਚੇਤਾਵਨੀਆਂ · IMD ’ਤੇ ਪੇਸ਼ਗੋਈ ਦੀਆਂ ਤਾਰੀਖਾਂ'],
  or:['ଏହା କିପରି କାମ କରେ','ଭାରତର ସରକାରୀ ଜିଲ୍ଲା ସତର୍କତା · IMDରେ ପୂର୍ବାନୁମାନ ତାରିଖ'],
  as:['এইটো কেনেকৈ কাম কৰে','ভাৰতজুৰি চৰকাৰী জিলা সতৰ্কবাণী · IMD-ত পূৰ্বানুমানৰ তাৰিখ'],
  ur:['یہ کیسے کام کرتا ہے','بھارت بھر کی سرکاری ضلعی تنبیہات · IMD پر پیش گوئی کی تاریخیں']
};
for(const [language,[aboutLink,sourceDetail]] of Object.entries(sourceLabels)) Object.assign(translated[language],{aboutLink,sourceDetail});

const copy = {en:base,...translated};
let currentLanguage='en';
const languageSelect=document.querySelector('#language');
const dialog=document.querySelector('#dialog');

function renderLanguage(language) {
  currentLanguage=copy[language]?language:'en';
  const strings=copy[currentLanguage];
  document.querySelectorAll('[data-i18n]').forEach(node=>{
    const value=strings[node.dataset.i18n] ?? base[node.dataset.i18n];
    if(value) node.innerHTML=value;
  });
  document.querySelectorAll('[data-i18n-aria]').forEach(node=>{
    const value=strings[node.dataset.i18nAria] ?? base[node.dataset.i18nAria];
    if(value) node.setAttribute('aria-label',value);
  });
  const languageTags={en:'en-IN',hi:'hi-IN',bn:'bn-IN',te:'te-IN',mr:'mr-IN',ta:'ta-IN',gu:'gu-IN',kn:'kn-IN',ml:'ml-IN',pa:'pa-IN',or:'or-IN',as:'as-IN',ur:'ur-IN',fr:'fr',es:'es',de:'de',zh:'zh-Hans',ja:'ja'};
  document.documentElement.lang=languageTags[currentLanguage]||'en-IN';
  document.documentElement.dir=currentLanguage==='ur'?'rtl':'ltr';
  try{localStorage.setItem('stormsignal-language',currentLanguage);}catch{}
}

languageSelect.addEventListener('change',event=>renderLanguage(event.target.value));
document.querySelectorAll('.close,.close-action').forEach(button=>button.addEventListener('click',()=>dialog.close()));
document.querySelector('#aboutButton').addEventListener('click',()=>dialog.showModal());
document.querySelector('#shareDemo').addEventListener('click',async()=>{
  const strings=copy[currentLanguage];
  const data={title:'StormSignal',text:strings.shareText,url:new URL('.',location.href).href};
  try{
    if(navigator.share) await navigator.share(data);
    else if(navigator.clipboard){await navigator.clipboard.writeText(`${data.text} ${data.url}`);window.alert(strings.shareDemo);}
    else window.prompt(strings.shareDemo,`${data.text} ${data.url}`);
  }catch(error){if(error.name!=='AbortError') window.prompt(strings.shareDemo,`${data.text} ${data.url}`);}
});

try {
  const saved=localStorage.getItem('stormsignal-language');
  if(saved&&copy[saved]) languageSelect.value=saved;
}catch{}
renderLanguage(languageSelect.value||'en');

let installPrompt=null;
const installButton=document.querySelector('#installApp');
window.addEventListener('beforeinstallprompt',event=>{
  event.preventDefault();
  installPrompt=event;
  installButton.hidden=false;
});
installButton.addEventListener('click',async()=>{
  if(!installPrompt) return;
  installPrompt.prompt();
  await installPrompt.userChoice;
  installPrompt=null;
  installButton.hidden=true;
});
window.addEventListener('appinstalled',()=>{
  installPrompt=null;
  installButton.hidden=true;
});
if('serviceWorker' in navigator && location.protocol.startsWith('http')) {
  window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
}

